import { sql } from 'drizzle-orm';
import { blob, check, foreignKey, index, integer, primaryKey, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const appMetadata = sqliteTable('app_metadata', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
});

export const teacherAccounts = sqliteTable('teacher_accounts', {
  id: text('id').primaryKey(),
  email: text('email').notNull(),
  passwordHash: text('password_hash').notNull(),
  createdAt: text('created_at').notNull(),
});

export const academicYears = sqliteTable('academic_years', {
  id: text('id').primaryKey(),
  ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id),
  label: text('label').notNull(),
  startsOn: text('starts_on').notNull(),
  endsOn: text('ends_on').notNull(),
  archivedAt: text('archived_at'),
  createdAt: text('created_at').notNull(),
}, (table) => [
  uniqueIndex('uq_academic_years_owner_label').on(table.ownerTeacherId, sql`${table.label} COLLATE NOCASE`),
  index('idx_academic_years_owner_archive_start').on(table.ownerTeacherId, table.archivedAt, table.startsOn),
]);

export const groups = sqliteTable('groups', {
  id: text('id').primaryKey(),
  ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id),
  academicYearId: text('academic_year_id').notNull().references(() => academicYears.id),
  name: text('name').notNull(),
  createdAt: text('created_at').notNull(),
}, (table) => [
  uniqueIndex('uq_groups_year_name').on(table.academicYearId, sql`${table.name} COLLATE NOCASE`),
  index('idx_groups_owner_year').on(table.ownerTeacherId, table.academicYearId),
]);

export const students = sqliteTable('students', {
  id: text('id').primaryKey(),
  groupId: text('group_id').notNull().references(() => groups.id),
  realName: text('real_name').notNull(),
  alias: text('alias').notNull(),
  avatar: text('avatar').notNull(),
  specialty: text('specialty'),
  archivedAt: text('archived_at'),
  groupCorrectionLockedAt: text('group_correction_locked_at'),
  createdAt: text('created_at').notNull(),
}, (table) => [
  uniqueIndex('uq_students_active_group_alias')
    .on(table.groupId, sql`${table.alias} COLLATE NOCASE`)
    .where(sql`${table.archivedAt} IS NULL`),
  index('idx_students_group_archive_alias_id').on(table.groupId, table.archivedAt, table.alias, table.id),
]);

const avatarColumns = {
  faceId: text('face_id').notNull(), skinToneId: text('skin_tone_id').notNull(), hairId: text('hair_id').notNull(),
  featureId: text('feature_id').notNull(), clothingId: text('clothing_id').notNull(), accessoryId: text('accessory_id').notNull(),
  frameId: text('frame_id').notNull(), backgroundId: text('background_id').notNull(),
};
export const avatarProfileVersions = sqliteTable('avatar_profile_versions', {
  profileStudentId: text('profile_student_id').notNull().references(() => students.id), revision: integer('revision').notNull(),
  ...avatarColumns, operation: text('operation').notNull(), revertedFromRevision: integer('reverted_from_revision'), reason: text('reason'),
  actorTeacherId: text('actor_teacher_id').notNull().references(() => teacherAccounts.id), createdAt: text('created_at').notNull(),
}, (table) => [primaryKey({ columns: [table.profileStudentId, table.revision] }), index('idx_avatar_profile_versions_student_created').on(table.profileStudentId, table.createdAt, table.revision), check('ck_avatar_profile_versions_revision', sql`${table.revision} >= 1`), check('ck_avatar_profile_versions_face', sql`${table.faceId} IN ('face-human', 'face-fox', 'face-owl', 'face-cat', 'face-wolf')`), check('ck_avatar_profile_versions_skin', sql`${table.skinToneId} IN ('skin-light', 'skin-medium-light', 'skin-medium', 'skin-medium-dark', 'skin-dark')`), check('ck_avatar_profile_versions_hair', sql`${table.hairId} IN ('hair-none', 'hair-short', 'hair-curly', 'hair-long', 'hair-braids')`), check('ck_avatar_profile_versions_feature', sql`${table.featureId} IN ('feature-none', 'feature-glasses', 'feature-freckles', 'feature-eclipse-mark')`), check('ck_avatar_profile_versions_clothing', sql`${table.clothingId} IN ('clothing-eclipse', 'clothing-field', 'clothing-orbit')`), check('ck_avatar_profile_versions_accessory', sql`${table.accessoryId} IN ('accessory-none', 'accessory-pin', 'accessory-comet', 'accessory-signal', 'accessory-compass', 'accessory-anchor', 'accessory-alliance')`), check('ck_avatar_profile_versions_frame', sql`${table.frameId} IN ('frame-none', 'frame-orbit', 'frame-emerald')`), check('ck_avatar_profile_versions_background', sql`${table.backgroundId} IN ('background-eclipse', 'background-night', 'background-dawn')`), check('ck_avatar_profile_versions_operation', sql`${table.operation} IN ('BACKFILL', 'CREATE', 'UPDATE', 'REVERT')`), check('ck_avatar_profile_versions_revert', sql`(${table.operation} = 'REVERT' AND ${table.revertedFromRevision} IS NOT NULL AND ${table.reason} IS NOT NULL) OR (${table.operation} <> 'REVERT' AND ${table.revertedFromRevision} IS NULL AND ${table.reason} IS NULL)`)]);
export const avatarProfiles = sqliteTable('avatar_profiles', {
  studentId: text('student_id').primaryKey().references(() => students.id), currentRevision: integer('current_revision').notNull(), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull(),
}, (table) => [foreignKey({ columns: [table.studentId, table.currentRevision], foreignColumns: [avatarProfileVersions.profileStudentId, avatarProfileVersions.revision], name: 'fk_avatar_profiles_current_revision' }), check('ck_avatar_profiles_revision', sql`${table.currentRevision} >= 1`)]);
export const avatarProfileRequests = sqliteTable('avatar_profile_requests', {
  ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id), idempotencyKey: text('idempotency_key').notNull(), operation: text('operation').notNull(), fingerprint: text('fingerprint').notNull(), studentId: text('student_id').notNull().references(() => students.id), resultingRevision: integer('resulting_revision'), createdAt: text('created_at').notNull(),
}, (table) => [primaryKey({ columns: [table.ownerTeacherId, table.idempotencyKey] }), index('idx_avatar_profile_requests_student_created').on(table.studentId, table.createdAt), check('ck_avatar_profile_requests_operation', sql`${table.operation} IN ('CREATE', 'UPDATE', 'REVERT')`)]);

export const xpEvidenceEvents = sqliteTable('xp_evidence_events', { id: text('id').primaryKey(), ownerTeacherId: text('owner_teacher_id').notNull(), studentId: text('student_id').notNull(), academicYearId: text('academic_year_id').notNull(), category: text('category').notNull(), baseXp: integer('base_xp').notNull(), realClassSessionId: text('real_class_session_id'), termId: text('term_id'), specialtyAtAward: text('specialty_at_award'), specialtyCategoryAtAward: text('specialty_category_at_award'), bonusEligibleAtAward: integer('bonus_eligible_at_award').notNull(), gemReceiptAllowedAtAward: integer('gem_receipt_allowed_at_award'), specialtyBonusXp: integer('specialty_bonus_xp').notNull(), effectiveXp: integer('effective_xp').notNull(), comment: text('comment'), createdAt: text('created_at').notNull(), createdByTeacherId: text('created_by_teacher_id').notNull(), clientRequestId: text('client_request_id').notNull(), requestFingerprint: text('request_fingerprint').notNull() }, (table) => [uniqueIndex('uq_xp_events_owner_request').on(table.ownerTeacherId, table.clientRequestId), index('idx_xp_events_student_year_created').on(table.studentId, table.academicYearId, table.createdAt, table.id), index('idx_xp_events_term_category_active').on(table.studentId, table.academicYearId, table.termId, table.category), check('ck_xp_events_attribution', sql`(${table.realClassSessionId} IS NULL AND ${table.termId} IS NULL) OR (${table.realClassSessionId} IS NOT NULL AND ${table.termId} IS NOT NULL)`), check('ck_xp_events_effective', sql`${table.effectiveXp} = ${table.baseXp} + ${table.specialtyBonusXp}`)]);
export const xpEvidenceReversals = sqliteTable('xp_evidence_reversals', { id: text('id').primaryKey(), ownerTeacherId: text('owner_teacher_id').notNull(), targetEventId: text('target_event_id').notNull(), reason: text('reason'), createdAt: text('created_at').notNull(), createdByTeacherId: text('created_by_teacher_id').notNull(), clientRequestId: text('client_request_id').notNull(), requestFingerprint: text('request_fingerprint').notNull() }, (table) => [uniqueIndex('uq_xp_reversals_target').on(table.targetEventId), uniqueIndex('uq_xp_reversals_owner_request').on(table.ownerTeacherId, table.clientRequestId)]);
export const xpLevelUnlocks = sqliteTable('xp_level_unlocks', { id: text('id').primaryKey(), studentId: text('student_id').notNull(), academicYearId: text('academic_year_id').notNull(), level: integer('level').notNull(), active: integer('active').notNull(), gemReceiptAllowed: integer('gem_receipt_allowed'), firstCrossedAt: text('first_crossed_at').notNull(), firstSourceEventId: text('first_source_event_id').notNull(), updatedAt: text('updated_at').notNull() }, (table) => [uniqueIndex('uq_xp_unlocks_student_year_level').on(table.studentId, table.academicYearId, table.level)]);
export const xpLevelGrantTransitions = sqliteTable('xp_level_grant_transitions', { id: text('id').primaryKey(), sequence: integer('sequence').notNull(), unlockId: text('unlock_id').notNull(), kind: text('kind').notNull(), sourceEventId: text('source_event_id'), sourceReversalId: text('source_reversal_id'), sourceTransitionId: text('source_transition_id'), occurredAt: text('occurred_at').notNull() }, (table) => [uniqueIndex('uq_xp_grant_transition_sequence').on(table.sequence), uniqueIndex('uq_xp_grant_transition_unlock').on(table.unlockId).where(sql`${table.kind} = 'GRANT'`), uniqueIndex('uq_xp_grant_transition_source').on(table.sourceTransitionId).where(sql`${table.sourceTransitionId} IS NOT NULL`)]);
export const xpBadgeUnlocks = sqliteTable('xp_badge_unlocks', { id: text('id').primaryKey(), studentId: text('student_id').notNull(), academicYearId: text('academic_year_id').notNull(), category: text('category').notNull(), badgeLabel: text('badge_label').notNull(), active: integer('active').notNull(), firstUnlockedAt: text('first_unlocked_at').notNull(), lastActivatedAt: text('last_activated_at').notNull(), lastRevokedAt: text('last_revoked_at'), sourceEventId: text('source_event_id') }, (table) => [uniqueIndex('uq_xp_badges_student_year_category').on(table.studentId, table.academicYearId, table.category)]);

export const observationRubricEvaluations = sqliteTable('observation_rubric_evaluations', {
  id: text('id').primaryKey(), studentId: text('student_id').notNull().references(() => students.id), termId: text('term_id').notNull(), calendarId: text('calendar_id').notNull(),
  ownerTeacherId: text('owner_teacher_id').notNull(), academicYearId: text('academic_year_id').notNull(), groupId: text('group_id').notNull(),
  state: text('state').notNull(), revision: integer('revision').notNull(),
  communicationOverride: integer('communication_override'), precisionOverride: integer('precision_override'), consistencyOverride: integer('consistency_override'), collaborationOverride: integer('collaboration_override'),
  draftComment: text('draft_comment'), currentSnapshotVersion: integer('current_snapshot_version'), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull(),
}, (table) => [uniqueIndex('uq_rubric_evaluations_student_term').on(table.studentId, table.termId), uniqueIndex('uq_rubric_evaluations_identity').on(table.id, table.ownerTeacherId, table.academicYearId, table.groupId, table.termId), index('idx_rubric_evaluations_owner_year_group').on(table.ownerTeacherId, table.academicYearId, table.groupId, table.termId)]);

export const observationRubricSnapshots = sqliteTable('observation_rubric_snapshots', {
  id: text('id').primaryKey(), evaluationId: text('evaluation_id').notNull().references(() => observationRubricEvaluations.id), version: integer('version').notNull(),
  communicationSuggested: integer('communication_suggested').notNull(), precisionSuggested: integer('precision_suggested').notNull(), consistencySuggested: integer('consistency_suggested').notNull(), collaborationSuggested: integer('collaboration_suggested').notNull(),
  communicationFinal: integer('communication_final').notNull(), precisionFinal: integer('precision_final').notNull(), consistencyFinal: integer('consistency_final').notNull(), collaborationFinal: integer('collaboration_final').notNull(),
  communicationBaseXp: integer('communication_base_xp').notNull(), precisionBaseXp: integer('precision_base_xp').notNull(), consistencyBaseXp: integer('consistency_base_xp').notNull(), collaborationBaseXp: integer('collaboration_base_xp').notNull(),
  communicationEventCount: integer('communication_event_count').notNull(), precisionEventCount: integer('precision_event_count').notNull(), consistencyEventCount: integer('consistency_event_count').notNull(), collaborationEventCount: integer('collaboration_event_count').notNull(),
  hasLowEvidence: integer('has_low_evidence').notNull(), levelSum: integer('level_sum').notNull(), gradeMilli: integer('grade_milli').notNull(), comment: text('comment'), closedAt: text('closed_at').notNull(), closedByTeacherId: text('closed_by_teacher_id').notNull(), priorVersion: integer('prior_version'),
}, (table) => [uniqueIndex('uq_rubric_snapshots_evaluation_version').on(table.evaluationId, table.version)]);

export const observationRubricSnapshotEvidence = sqliteTable('observation_rubric_snapshot_evidence', {
  snapshotId: text('snapshot_id').notNull().references(() => observationRubricSnapshots.id), xpEventId: text('xp_event_id').notNull().references(() => xpEvidenceEvents.id), category: text('category').notNull(), baseXp: integer('base_xp').notNull(),
}, (table) => [primaryKey({ columns: [table.snapshotId, table.xpEventId], name: 'pk_rubric_snapshot_evidence' })]);

export const observationRubricLifecycleEvents = sqliteTable('observation_rubric_lifecycle_events', {
  id: text('id').primaryKey(), evaluationId: text('evaluation_id').notNull().references(() => observationRubricEvaluations.id), operation: text('operation').notNull(), resultingRevision: integer('resulting_revision').notNull(), resultingState: text('resulting_state').notNull(), snapshotVersion: integer('snapshot_version'), reason: text('reason'), actorTeacherId: text('actor_teacher_id').notNull(), occurredAt: text('occurred_at').notNull(),
}, (table) => [index('idx_rubric_lifecycle_evaluation').on(table.evaluationId, table.occurredAt)]);

export const observationRubricRequests = sqliteTable('observation_rubric_requests', {
  id: text('id').primaryKey(), ownerTeacherId: text('owner_teacher_id').notNull(), idempotencyKey: text('idempotency_key').notNull(), operation: text('operation').notNull(), fingerprint: text('fingerprint').notNull(), evaluationId: text('evaluation_id'), resultingRevision: integer('resulting_revision'), snapshotVersion: integer('snapshot_version'), createdAt: text('created_at').notNull(),
}, (table) => [uniqueIndex('uq_rubric_requests_owner_key').on(table.ownerTeacherId, table.idempotencyKey)]);

export const coinLedger = sqliteTable('coin_ledger', { id: text('id').primaryKey(), studentId: text('student_id').notNull().references(() => students.id), academicYearId: text('academic_year_id').notNull().references(() => academicYears.id), amount: integer('amount').notNull(), source: text('source').notNull(), correctionOfId: text('correction_of_id'), redemptionId: text('redemption_id'), sourceTransitionId: text('source_transition_id'), createdAt: text('created_at').notNull(), ownerTeacherId: text('owner_teacher_id').references(() => teacherAccounts.id), clientRequestId: text('client_request_id'), requestFingerprint: text('request_fingerprint') }, (table) => [uniqueIndex('uq_coin_ledger_owner_request').on(table.ownerTeacherId, table.clientRequestId).where(sql`${table.ownerTeacherId} IS NOT NULL AND ${table.clientRequestId} IS NOT NULL`), uniqueIndex('uq_coin_ledger_manual_correction_target').on(table.correctionOfId).where(sql`${table.source} = 'MANUAL_CORRECTION'`)]);
export const assessmentContexts = sqliteTable('assessment_contexts', { id: text('id').primaryKey(), groupId: text('group_id').notNull().references(() => groups.id), name: text('name').notNull(), archivedAt: text('archived_at'), createdAt: text('created_at').notNull() }, (table) => [uniqueIndex('uq_assessment_contexts_active_group_normalized_name').on(table.groupId, sql`lower(trim(${table.name}))`).where(sql`${table.archivedAt} IS NULL`)]);
export const coinRewards = sqliteTable('coin_rewards', { id: text('id').primaryKey(), name: text('name').notNull(), cost: integer('cost').notNull(), type: text('type').notNull() });
export const advantageRedemptions = sqliteTable('advantage_redemptions', { id: text('id').primaryKey(), studentId: text('student_id').notNull().references(() => students.id), assessmentContextId: text('assessment_context_id').notNull().references(() => assessmentContexts.id), rewardId: text('reward_id').notNull().references(() => coinRewards.id), cost: integer('cost').notNull(), debitLedgerId: text('debit_ledger_id').notNull().references(() => coinLedger.id), reversalLedgerId: text('reversal_ledger_id').references(() => coinLedger.id), createdAt: text('created_at').notNull(), reversedAt: text('reversed_at'), ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id), clientRequestId: text('client_request_id'), requestFingerprint: text('request_fingerprint') });
export const coinSpendAllocations = sqliteTable('coin_spend_allocations', { id: text('id').primaryKey(), redemptionId: text('redemption_id').notNull().references(() => advantageRedemptions.id), grantLedgerEntryId: text('grant_ledger_entry_id').notNull().references(() => coinLedger.id), releasedAt: text('released_at'), releaseReason: text('release_reason'), createdAt: text('created_at').notNull() });
export const classroomEvents = sqliteTable('classroom_events', { id: text('id').primaryKey(), ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id), groupId: text('group_id').notNull().references(() => groups.id), title: text('title').notNull(), description: text('description').notNull(), status: text('status').notNull(), showOnProjection: integer('show_on_projection').notNull().default(0), theme: text('theme').notNull().default('MISSION'), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull(), activatedAt: text('activated_at'), completedAt: text('completed_at'), archivedAt: text('archived_at'), clientRequestId: text('client_request_id'), requestFingerprint: text('request_fingerprint') }, (table) => [index('idx_classroom_events_group_status_updated').on(table.groupId, table.status, table.updatedAt, table.id), uniqueIndex('uq_classroom_events_owner_request').on(table.ownerTeacherId, table.clientRequestId).where(sql`${table.ownerTeacherId} IS NOT NULL AND ${table.clientRequestId} IS NOT NULL`), check('ck_classroom_events_status', sql`${table.status} IN ('DRAFT', 'ACTIVE', 'COMPLETED')`), check('ck_classroom_events_projection', sql`${table.showOnProjection} IN (0, 1)`)]);
export const classroomChallenges = sqliteTable('classroom_challenges', { id: text('id').primaryKey(), ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id), groupId: text('group_id').notNull().references(() => groups.id), title: text('title').notNull(), description: text('description').notNull(), target: integer('target').notNull(), progress: integer('progress').notNull().default(0), status: text('status').notNull(), showOnProjection: integer('show_on_projection').notNull().default(0), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull(), activatedAt: text('activated_at'), completedAt: text('completed_at'), archivedAt: text('archived_at') }, (table) => [index('idx_classroom_challenges_group_status_updated').on(table.groupId, table.status, table.updatedAt, table.id), check('ck_classroom_challenges_target', sql`${table.target} > 0`), check('ck_classroom_challenges_progress', sql`${table.progress} >= 0 AND ${table.progress} <= ${table.target}`), check('ck_classroom_challenges_status', sql`${table.status} IN ('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED')`), check('ck_classroom_challenges_projection', sql`${table.showOnProjection} IN (0, 1)`)]);
export const minigameSessions = sqliteTable('minigame_sessions', { id: text('id').primaryKey(), ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id), groupId: text('group_id').notNull().references(() => groups.id), kind: text('kind').notNull(), title: text('title').notNull(), prompt: text('prompt').notNull(), durationSeconds: integer('duration_seconds').notNull().default(0), status: text('status').notNull(), remainingSeconds: integer('remaining_seconds').notNull().default(0), startedAt: text('started_at'), pausedAt: text('paused_at'), selectedStudentId: text('selected_student_id').references(() => students.id), drawOrder: text('draw_order').notNull().default('[]'), drawIndex: integer('draw_index').notNull().default(0), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull(), teamCount: integer('team_count').notNull().default(0), teamAssignments: text('team_assignments').notNull().default('{}'), promptDeckPrompts: text('prompt_deck_prompts').notNull().default('[]'), promptRevealed: integer('prompt_revealed').notNull().default(1) }, (table) => [uniqueIndex('uq_minigame_active_group').on(table.groupId).where(sql`${table.status} IN ('READY', 'RUNNING', 'PAUSED')`), index('idx_minigame_sessions_group_updated').on(table.groupId, table.updatedAt, table.id), check('ck_minigame_kind', sql`${table.kind} IN ('RANDOM_DRAW', 'FRENCH_SPRINT', 'TEAM_DRAW', 'PROMPT_DECK')`), check('ck_minigame_status', sql`${table.status} IN ('READY', 'RUNNING', 'PAUSED', 'ENDED')`), check('ck_minigame_duration', sql`${table.durationSeconds} >= 0`), check('ck_minigame_remaining', sql`${table.remainingSeconds} >= 0`), check('ck_minigame_draw_index', sql`${table.drawIndex} >= 0`), check('ck_minigame_team_count', sql`${table.teamCount} >= 0`), check('ck_minigame_prompt_revealed', sql`${table.promptRevealed} IN (0, 1)`)]);
export const minigamePresets = sqliteTable('minigame_presets', { id: text('id').primaryKey(), ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id), title: text('title').notNull(), prompt: text('prompt').notNull(), durationSeconds: integer('duration_seconds').notNull(), archivedAt: text('archived_at'), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() }, (table) => [index('idx_minigame_presets_owner_archive_updated').on(table.ownerTeacherId, table.archivedAt, table.updatedAt, table.id)]);
export const promptDecks = sqliteTable('prompt_decks', { id: text('id').primaryKey(), ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id), title: text('title').notNull(), prompts: text('prompts').notNull(), archivedAt: text('archived_at'), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() }, (table) => [index('idx_prompt_decks_owner_archive_updated').on(table.ownerTeacherId, table.archivedAt, table.updatedAt, table.id)]);

export const academicCalendars = sqliteTable('academic_calendars', { id: text('id').primaryKey(), academicYearId: text('academic_year_id').notNull(), ownerTeacherId: text('owner_teacher_id').notNull(), timezone: text('timezone').notNull(), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() }, (table) => [uniqueIndex('uq_calendar_year').on(table.academicYearId)]);
export const academicTerms = sqliteTable('academic_terms', { id: text('id').primaryKey(), calendarId: text('calendar_id').notNull(), academicYearId: text('academic_year_id').notNull(), ownerTeacherId: text('owner_teacher_id').notNull(), code: text('code').notNull(), startsOn: text('starts_on').notNull(), endsOn: text('ends_on').notNull() });
export const calendarHolidays = sqliteTable('calendar_holidays', { id: text('id').primaryKey(), calendarId: text('calendar_id').notNull(), academicYearId: text('academic_year_id').notNull(), ownerTeacherId: text('owner_teacher_id').notNull(), startsOn: text('starts_on').notNull(), endsOn: text('ends_on').notNull() });
export const weeklyTimetableSlots = sqliteTable('weekly_timetable_slots', { id: text('id').primaryKey(), calendarId: text('calendar_id').notNull(), academicYearId: text('academic_year_id').notNull(), ownerTeacherId: text('owner_teacher_id').notNull(), groupId: text('group_id').notNull(), weekday: integer('weekday').notNull(), startsAt: text('starts_at').notNull(), endsAt: text('ends_at').notNull() });
export const realClassSessions = sqliteTable('real_class_sessions', { id: text('id').primaryKey(), ownerTeacherId: text('owner_teacher_id').notNull(), academicYearId: text('academic_year_id').notNull(), groupId: text('group_id').notNull(), calendarId: text('calendar_id').notNull(), termId: text('term_id').notNull(), slotId: text('slot_id').notNull(), localDate: text('local_date').notNull(), timezone: text('timezone').notNull(), slotStartsAt: text('slot_starts_at').notNull(), slotEndsAt: text('slot_ends_at').notNull(), startedAt: text('started_at').notNull(), endedAt: text('ended_at'), behaviourSnapshotVersion: integer('behaviour_snapshot_version'), createdAt: text('created_at').notNull() });
export const realClassSessionRequests = sqliteTable('real_class_session_requests', { id: text('id').primaryKey(), ownerTeacherId: text('owner_teacher_id').notNull(), idempotencyKey: text('idempotency_key').notNull(), operation: text('operation').notNull(), fingerprint: text('fingerprint').notNull(), sessionId: text('session_id').notNull(), createdAt: text('created_at').notNull() }, (table) => [uniqueIndex('uq_session_request_owner_key').on(table.ownerTeacherId, table.idempotencyKey)]);
export const realClassSessionRtRoster = sqliteTable('real_class_session_rt_roster', { sessionId: text('session_id').notNull(), studentId: text('student_id').notNull(), ownerTeacherId: text('owner_teacher_id').notNull(), academicYearId: text('academic_year_id').notNull(), groupId: text('group_id').notNull(), termId: text('term_id').notNull() });
export const rtEntries = sqliteTable('rt_entries', { id: text('id').primaryKey(), sessionId: text('session_id').notNull(), studentId: text('student_id').notNull(), termId: text('term_id').notNull(), value: text('value').notNull(), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() });
export const rtRequests = sqliteTable('rt_requests', { id: text('id').primaryKey(), ownerTeacherId: text('owner_teacher_id').notNull(), idempotencyKey: text('idempotency_key').notNull(), operation: text('operation').notNull(), sessionId: text('session_id').notNull(), fingerprint: text('fingerprint').notNull(), createdAt: text('created_at').notNull() }, (table) => [uniqueIndex('uq_rt_request_owner_key').on(table.ownerTeacherId, table.idempotencyKey)]);
export const rtStreakEmeraldEntitlements = sqliteTable('rt_streak_emerald_entitlements', { id: text('id').primaryKey(), sourceKey: text('source_key').notNull(), sourceEntryId: text('source_entry_id').notNull(), studentId: text('student_id').notNull(), termId: text('term_id').notNull(), active: integer('active').notNull(), revision: integer('revision').notNull(), gemReceiptAllowed: integer('gem_receipt_allowed'), consumerId: text('consumer_id'), grantId: text('grant_id'), consumedRevision: integer('consumed_revision'), consumedAt: text('consumed_at') }, (table) => [uniqueIndex('uq_rt_entitlement_source_key').on(table.sourceKey)]);

export const gemLedger = sqliteTable('gem_ledger', {
  id: text('id').primaryKey(), studentId: text('student_id').notNull().references(() => students.id),
  academicYearId: text('academic_year_id').notNull().references(() => academicYears.id), currency: text('currency').notNull(),
  amount: integer('amount').notNull(), movementKind: text('movement_kind').notNull(), sourceKind: text('source_kind').notNull(),
  sourceId: text('source_id').notNull(), sourceFamilyId: text('source_family_id').notNull(), unitIndex: integer('unit_index').notNull(),
  correctionOfId: text('correction_of_id'), requestKey: text('request_key'), requestFingerprint: text('request_fingerprint'),
  createdAt: text('created_at').notNull(), ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id),
}, (table) => [uniqueIndex('uq_gem_ledger_source_unit').on(table.sourceKind, table.sourceId, table.unitIndex), uniqueIndex('uq_gem_ledger_correction').on(table.correctionOfId), index('idx_gem_ledger_student_year_currency_created').on(table.studentId, table.academicYearId, table.currency, table.createdAt, table.id)]);
export const gemReconciliationCursors = sqliteTable('gem_reconciliation_cursors', { stream: text('stream').primaryKey(), lastSequence: integer('last_sequence').notNull(), updatedAt: text('updated_at').notNull() });
export const gemXpTransitionReceipts = sqliteTable('gem_xp_transition_receipts', { transitionId: text('transition_id').primaryKey(), sequence: integer('sequence').notNull(), unlockId: text('unlock_id').notNull(), kind: text('kind').notNull(), sourceEventId: text('source_event_id'), sourceReversalId: text('source_reversal_id'), outcome: text('outcome').notNull(), movementId: text('movement_id'), fingerprint: text('fingerprint').notNull(), createdAt: text('created_at').notNull() }, (table) => [uniqueIndex('uq_gem_xp_receipt_sequence').on(table.sequence)]);
export const gemRewardCatalogue = sqliteTable('gem_reward_catalogue', { id: text('id').primaryKey(), currency: text('currency').notNull(), cost: integer('cost').notNull() }, (table) => [uniqueIndex('uq_gem_reward_currency').on(table.currency)]);
export const gemResultRewards = sqliteTable('gem_result_rewards', { id: text('id').primaryKey(), studentId: text('student_id').notNull().references(() => students.id), assessmentContextId: text('assessment_context_id').notNull().references(() => assessmentContexts.id), academicYearId: text('academic_year_id').notNull().references(() => academicYears.id), tier: text('tier').notNull(), state: text('state').notNull(), ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id), createdAt: text('created_at').notNull() }, (table) => [uniqueIndex('uq_gem_result_reward_identity').on(table.studentId, table.assessmentContextId, table.academicYearId)]);
export const gemResultRewardOperations = sqliteTable('gem_result_reward_operations', { operationId: text('operation_id').primaryKey(), rewardId: text('reward_id').notNull().references(() => gemResultRewards.id), operation: text('operation').notNull(), requestKey: text('request_key').notNull(), requestFingerprint: text('request_fingerprint').notNull(), reason: text('reason'), priorTier: text('prior_tier').notNull(), resultingTier: text('resulting_tier').notNull(), movementIds: text('movement_ids').notNull(), createdAt: text('created_at').notNull() }, (table) => [uniqueIndex('uq_gem_result_operation_request').on(table.requestKey), uniqueIndex('uq_gem_result_operation_kind').on(table.rewardId, table.operation)]);
export const gemAdvantageRedemptions = sqliteTable('gem_advantage_redemptions', { id: text('id').primaryKey(), studentId: text('student_id').notNull().references(() => students.id), assessmentContextId: text('assessment_context_id').notNull().references(() => assessmentContexts.id), academicYearId: text('academic_year_id').notNull().references(() => academicYears.id), currency: text('currency').notNull(), cost: integer('cost').notNull(), requestKey: text('request_key').notNull(), requestFingerprint: text('request_fingerprint').notNull(), state: text('state').notNull(), ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id), createdAt: text('created_at').notNull(), reversalOperationId: text('reversal_operation_id'), reversalRequestKey: text('reversal_request_key'), reversalFingerprint: text('reversal_fingerprint'), reversalTrigger: text('reversal_trigger'), reversalReason: text('reversal_reason'), reversedAt: text('reversed_at') }, (table) => [uniqueIndex('uq_gem_advantage_context').on(table.studentId, table.assessmentContextId, table.academicYearId), uniqueIndex('uq_gem_advantage_request').on(table.ownerTeacherId, table.requestKey)]);
export const gemSpendAllocations = sqliteTable('gem_spend_allocations', { id: text('id').primaryKey(), redemptionId: text('redemption_id').notNull().references(() => gemAdvantageRedemptions.id), fundingMovementId: text('funding_movement_id').notNull().references(() => gemLedger.id), spendMovementId: text('spend_movement_id').notNull().unique(), spendReversalMovementId: text('spend_reversal_movement_id'), createdAt: text('created_at').notNull(), releasedAt: text('released_at'), releaseReason: text('release_reason') }, (table) => [uniqueIndex('uq_gem_allocation_redemption_funding').on(table.redemptionId, table.fundingMovementId)]);

export const groupTermClosures = sqliteTable('group_term_closures', {
  id: text('id').primaryKey(), ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id),
  academicYearId: text('academic_year_id').notNull(), groupId: text('group_id').notNull(), calendarId: text('calendar_id').notNull(), termId: text('term_id').notNull(),
  state: text('state').notNull(), revision: integer('revision').notNull(), currentSnapshotVersion: integer('current_snapshot_version'), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull(),
}, (table) => [uniqueIndex('uq_group_term_close_identity').on(table.groupId, table.academicYearId, table.termId), uniqueIndex('uq_group_term_close_lineage').on(table.id, table.ownerTeacherId, table.academicYearId, table.groupId, table.calendarId, table.termId), check('ck_group_term_close_state', sql`${table.state} IN ('OPEN', 'CLOSED', 'REOPENED')`), check('ck_group_term_close_revision', sql`${table.revision} >= 0`)]);

export const groupTermCloseSnapshots = sqliteTable('group_term_close_snapshots', {
  id: text('id').primaryKey(), closureId: text('closure_id').notNull().references(() => groupTermClosures.id), version: integer('version').notNull(), priorVersion: integer('prior_version'), cohortCount: integer('cohort_count').notNull(), closedByTeacherId: text('closed_by_teacher_id').notNull().references(() => teacherAccounts.id), closedAt: text('closed_at').notNull(), xlsxBytes: blob('xlsx_bytes', { mode: 'buffer' }).notNull(), xlsxSha256: text('xlsx_sha256').notNull(), xlsxLength: integer('xlsx_length').notNull(),
}, (table) => [uniqueIndex('uq_group_term_close_snapshot_version').on(table.closureId, table.version), check('ck_group_term_close_snapshot_version', sql`${table.version} > 0`), check('ck_group_term_close_snapshot_prior', sql`${table.priorVersion} IS NULL OR (${table.priorVersion} > 0 AND ${table.version} = ${table.priorVersion} + 1)`), check('ck_group_term_close_snapshot_count', sql`${table.cohortCount} >= 0`), check('ck_group_term_close_snapshot_length', sql`${table.xlsxLength} >= 0`)]);

export const groupTermCloseStudents = sqliteTable('group_term_close_students', {
  id: text('id').primaryKey(), snapshotId: text('snapshot_id').notNull().references(() => groupTermCloseSnapshots.id), studentId: text('student_id').notNull().references(() => students.id), ordinal: integer('ordinal').notNull(), realName: text('real_name').notNull(), evaluationId: text('evaluation_id').notNull(), evaluationSnapshotVersion: integer('evaluation_snapshot_version').notNull(), gradeMilli: integer('grade_milli').notNull(), rtSum: integer('rt_sum'), rtEvaluatedCount: integer('rt_evaluated_count').notNull(),
}, (table) => [uniqueIndex('uq_group_term_close_student_ordinal').on(table.snapshotId, table.ordinal), uniqueIndex('uq_group_term_close_student').on(table.snapshotId, table.studentId), check('ck_group_term_close_student_ordinal', sql`${table.ordinal} > 0`), check('ck_group_term_close_student_grade', sql`${table.gradeMilli} BETWEEN 0 AND 10000`), check('ck_group_term_close_student_rt', sql`(${table.rtSum} IS NULL AND ${table.rtEvaluatedCount} = 0) OR (${table.rtSum} IS NOT NULL AND ${table.rtEvaluatedCount} > 0)`)]);

export const groupTermCloseRtEvidence = sqliteTable('group_term_close_rt_evidence', {
  id: text('id').primaryKey(), snapshotId: text('snapshot_id').notNull().references(() => groupTermCloseSnapshots.id), studentId: text('student_id').notNull().references(() => students.id), entryId: text('entry_id').notNull(), value: text('value').notNull(),
}, (table) => [uniqueIndex('uq_group_term_close_rt_evidence').on(table.snapshotId, table.studentId, table.entryId), check('ck_group_term_close_rt_value', sql`${table.value} IN ('10', '5', '0', 'ABSENT')`)]);

export const groupTermCloseLifecycleEvents = sqliteTable('group_term_close_lifecycle_events', {
  id: text('id').primaryKey(), closureId: text('closure_id').notNull().references(() => groupTermClosures.id), operation: text('operation').notNull(), resultingRevision: integer('resulting_revision').notNull(), resultingState: text('resulting_state').notNull(), snapshotVersion: integer('snapshot_version'), reason: text('reason'), actorTeacherId: text('actor_teacher_id').notNull().references(() => teacherAccounts.id), occurredAt: text('occurred_at').notNull(),
}, (table) => [check('ck_group_term_close_lifecycle_operation', sql`${table.operation} IN ('CLOSE', 'REOPEN')`), check('ck_group_term_close_lifecycle_state', sql`${table.resultingState} IN ('OPEN', 'CLOSED', 'REOPENED')`), check('ck_group_term_close_lifecycle_revision', sql`${table.resultingRevision} >= 0`)]);

export const groupTermCloseRequests = sqliteTable('group_term_close_requests', {
  id: text('id').primaryKey(), ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id), idempotencyKey: text('idempotency_key').notNull(), operation: text('operation').notNull(), closureId: text('closure_id').references(() => groupTermClosures.id), fingerprint: text('fingerprint').notNull(), resultingRevision: integer('resulting_revision'), snapshotVersion: integer('snapshot_version'), createdAt: text('created_at').notNull(),
}, (table) => [uniqueIndex('uq_group_term_close_request_owner_key').on(table.ownerTeacherId, table.idempotencyKey), check('ck_group_term_close_request_operation', sql`${table.operation} IN ('CLOSE', 'REOPEN')`)]);

export const boutiquePurchases = sqliteTable('boutique_purchases', {
  id: text('id').primaryKey(), ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id), studentId: text('student_id').notNull().references(() => students.id), academicYearId: text('academic_year_id').notNull().references(() => academicYears.id), termId: text('term_id').notNull().references(() => academicTerms.id), itemId: text('item_id').notNull(), catalogueVersion: text('catalogue_version').notNull(), currency: text('currency').notNull(), cost: integer('cost').notNull(), minLevel: integer('min_level').notNull(), requiredSpecialtyCategory: text('required_specialty_category'), availableFromTerm: text('available_from_term').notNull(), levelAtPurchase: integer('level_at_purchase').notNull(), specialtyCategoryAtPurchase: text('specialty_category_at_purchase'), purchasedAt: text('purchased_at').notNull(), actorTeacherId: text('actor_teacher_id').notNull().references(() => teacherAccounts.id),
}, (table) => [uniqueIndex('uq_boutique_purchases_student_year_item').on(table.studentId, table.academicYearId, table.itemId), index('idx_boutique_purchases_student_year').on(table.studentId, table.academicYearId, table.purchasedAt, table.id), index('idx_boutique_purchases_owner_year').on(table.ownerTeacherId, table.academicYearId, table.purchasedAt, table.id), check('ck_boutique_purchases_currency', sql`${table.currency} = 'EMERALD'`), check('ck_boutique_purchases_cost', sql`${table.cost} BETWEEN 1 AND 3`)]);
export const boutiquePurchaseRequests = sqliteTable('boutique_purchase_requests', {
  ownerTeacherId: text('owner_teacher_id').notNull().references(() => teacherAccounts.id), idempotencyKey: text('idempotency_key').notNull(), operation: text('operation').notNull(), fingerprint: text('fingerprint').notNull(), studentId: text('student_id').notNull().references(() => students.id), academicYearId: text('academic_year_id').notNull().references(() => academicYears.id), itemId: text('item_id').notNull(), termId: text('term_id').notNull().references(() => academicTerms.id), purchaseId: text('purchase_id').notNull().references(() => boutiquePurchases.id), resultingEmeraldBalance: integer('resulting_emerald_balance').notNull(), createdAt: text('created_at').notNull(),
}, (table) => [primaryKey({ columns: [table.ownerTeacherId, table.idempotencyKey] }), uniqueIndex('uq_boutique_purchase_requests_purchase').on(table.purchaseId), index('idx_boutique_purchase_requests_student_created').on(table.studentId, table.academicYearId, table.createdAt), check('ck_boutique_purchase_requests_operation', sql`${table.operation} = 'PURCHASE'`), check('ck_boutique_purchase_requests_fingerprint', sql`length(trim(${table.fingerprint})) > 0`)]);
export const boutiqueSpendAllocations = sqliteTable('boutique_spend_allocations', {
  id: text('id').primaryKey(), purchaseId: text('purchase_id').notNull().references(() => boutiquePurchases.id), fundingMovementId: text('funding_movement_id').notNull().references(() => gemLedger.id), spendMovementId: text('spend_movement_id').notNull().references(() => gemLedger.id), createdAt: text('created_at').notNull(),
}, (table) => [uniqueIndex('uq_boutique_spend_allocations_purchase_funding').on(table.purchaseId, table.fundingMovementId), uniqueIndex('uq_boutique_spend_allocations_funding').on(table.fundingMovementId), uniqueIndex('uq_boutique_spend_allocations_spend').on(table.spendMovementId), index('idx_boutique_spend_allocations_funding').on(table.fundingMovementId)]);
