import { randomUUID } from 'node:crypto';
import type Database from 'better-sqlite3';
import { ApiError } from '../http/errors.js';
import * as repository from './repository.js';

export const AVATARS = ['default', 'fox', 'owl', 'cat', 'wolf'] as const;
export const SPECIALTIES = ['Leader', 'Diplomat', 'Strategist', 'Analyst', 'Disciplined', 'Perseverant', 'Helper', 'Ally'] as const;
export type StudentDraft = { realName: string; alias: string; avatar?: typeof AVATARS[number]; specialty?: typeof SPECIALTIES[number] | null };
const now = () => new Date().toISOString();
const conflict = (error: unknown): never => { if (error instanceof ApiError) throw error; if (error instanceof Error && /UNIQUE|constraint/i.test(error.message)) throw new ApiError('CONFLICT', 409, 'The resource conflicts with an existing record.'); throw error; };
const notFound = (message: string): never => { throw new ApiError('NOT_FOUND', 404, message); };
const validation = (message: string): never => { throw new ApiError('VALIDATION_FAILED', 422, message); };
function ownedYear(db: Database.Database, id: string, teacherId: string) { return repository.findYear(db, id, teacherId) ?? notFound('Academic year not found.'); }
export function getYearForPatch(db: Database.Database, teacherId: string, id: string) { return ownedYear(db, id, teacherId); }
function ownedGroup(db: Database.Database, id: string, teacherId: string) { return repository.findGroup(db, id, teacherId) ?? notFound('Group not found.'); }
function groupYear(db: Database.Database, group: repository.GroupRecord, teacherId: string) { const year = ownedYear(db, group.academicYearId, teacherId); return { group, year }; }
function ownedStudentContext(db: Database.Database, id: string, teacherId: string) { const student = repository.findOwnedStudent(db, id, teacherId) ?? notFound('Student not found.'); const group = ownedGroup(db, student.groupId, teacherId); return { student, ...groupYear(db, group, teacherId) }; }

/** Minimal cross-domain adapter. XP must not depend on roster table details. */
export function getOwnedStudentAcademicYearContext(db: Database.Database, teacherId: string, studentId: string) {
  const context = ownedStudentContext(db, studentId, teacherId);
  return { student: context.student, group: context.group, year: context.year };
}
export function getOwnedStudentAcademicYearContextForYear(db: Database.Database, teacherId: string, studentId: string, academicYearId: string) {
  const student = db.prepare(`SELECT s.id, s.group_id AS groupId, s.real_name AS realName, s.alias, s.avatar, s.specialty, s.archived_at AS archivedAt, s.group_correction_locked_at AS groupCorrectionLockedAt, s.created_at AS createdAt FROM students s JOIN groups g ON g.id=s.group_id JOIN academic_years y ON y.id=g.academic_year_id WHERE s.id=? AND y.id=? AND y.owner_teacher_id=?`).get(studentId, academicYearId, teacherId) as repository.StudentRecord | undefined;
  if (!student) throw new ApiError('NOT_FOUND', 404, 'Student not found.');
  const group = ownedGroup(db, student.groupId, teacherId); const year = ownedYear(db, academicYearId, teacherId); return { student, group, year };
}

export function createYear(db: Database.Database, teacherId: string, input: { label: string; startsOn: string; endsOn: string }) { const value = { label: input.label.trim(), startsOn: input.startsOn.trim(), endsOn: input.endsOn.trim() }; if (!value.label || value.startsOn >= value.endsOn) validation('Academic year values are invalid.'); try { return repository.insertYear(db, { id: randomUUID(), ownerTeacherId: teacherId, ...value, archivedAt: null, createdAt: now() }); } catch (error) { return conflict(error); } }
export function listAcademicYears(db: Database.Database, teacherId: string, includeArchived: boolean) { return repository.listYears(db, teacherId, includeArchived); }
export function updateYear(db: Database.Database, teacherId: string, id: string, input: { label: string; startsOn: string; endsOn: string }) { const year = ownedYear(db, id, teacherId); const value = { label: input.label.trim(), startsOn: input.startsOn.trim(), endsOn: input.endsOn.trim() }; if (year.archivedAt) validation('Archived academic years are read-only.'); if (!value.label || value.startsOn >= value.endsOn) validation('Academic year values are invalid.'); try { repository.updateYear(db, id, value); return { ...year, ...value }; } catch (error) { return conflict(error); } }
export function archiveAcademicYear(db: Database.Database, teacherId: string, id: string) { const year = ownedYear(db, id, teacherId); if (year.archivedAt) validation('Academic year is already archived.'); repository.archiveYear(db, id, now()); }
export function createGroup(db: Database.Database, teacherId: string, yearId: string, name: string) { const year = ownedYear(db, yearId, teacherId); const value = name.trim(); if (year.archivedAt || !value) validation('Academic year is not writable or group name is empty.'); try { return repository.insertGroup(db, { id: randomUUID(), ownerTeacherId: teacherId, academicYearId: yearId, name: value, createdAt: now() }); } catch (error) { return conflict(error); } }
export function listAcademicGroups(db: Database.Database, teacherId: string, yearId: string) { ownedYear(db, yearId, teacherId); return repository.listGroups(db, yearId, teacherId); }
export function updateGroup(db: Database.Database, teacherId: string, id: string, name: string) { const group = ownedGroup(db, id, teacherId); const year = ownedYear(db, group.academicYearId, teacherId); const value = name.trim(); if (year.archivedAt || !value) validation('Archived academic years are read-only or group name is empty.'); try { repository.updateGroup(db, id, value); return { ...group, name: value }; } catch (error) { return conflict(error); } }
function writableGroup(db: Database.Database, teacherId: string, groupId: string) { const group = ownedGroup(db, groupId, teacherId); const year = ownedYear(db, group.academicYearId, teacherId); if (year.archivedAt) validation('Archived academic years are read-only.'); return { group, year }; }
export function createStudents(db: Database.Database, teacherId: string, groupId: string, drafts: StudentDraft[]) { const { group } = writableGroup(db, teacherId, groupId); if (drafts.length < 1 || drafts.length > 30) validation('Student batches must contain between 1 and 30 students.'); const values = drafts.map((draft) => ({ ...draft, realName: draft.realName.trim(), alias: draft.alias.trim(), specialty: draft.specialty?.trim() || null })); const aliases = new Set<string>(); for (const draft of values) { if (!draft.realName || !draft.alias || aliases.has(draft.alias.toLocaleLowerCase())) validation('Student names and aliases must be unique and non-empty.'); aliases.add(draft.alias.toLocaleLowerCase()); } try { return repository.withTransaction(db, () => values.map((draft) => repository.insertStudent(db, { id: randomUUID(), groupId: group.id, realName: draft.realName, alias: draft.alias, avatar: draft.avatar ?? 'default', specialty: draft.specialty ?? null, archivedAt: null, groupCorrectionLockedAt: null, createdAt: now() }))); } catch (error) { return conflict(error); } }
export function listGroupStudents(db: Database.Database, teacherId: string, groupId: string, includeArchived: boolean) { ownedGroup(db, groupId, teacherId); return repository.listStudents(db, groupId, includeArchived); }
export function getStudent(db: Database.Database, teacherId: string, id: string) { return ownedStudentContext(db, id, teacherId).student; }
export function updateStudent(db: Database.Database, teacherId: string, id: string, input: Pick<StudentDraft, 'realName' | 'alias' | 'avatar' | 'specialty'>) { const { student, year } = ownedStudentContext(db, id, teacherId); const value = { realName: input.realName.trim(), alias: input.alias.trim(), avatar: input.avatar ?? 'default', specialty: input.specialty?.trim() || null }; if (student.archivedAt || year.archivedAt || !value.realName || !value.alias) validation('Archived students and years are read-only or student values are empty.'); try { repository.updateStudent(db, id, value); return { ...student, ...value }; } catch (error) { return conflict(error); } }
export function archiveStudentRecord(db: Database.Database, teacherId: string, id: string) { const { student, year } = ownedStudentContext(db, id, teacherId); if (student.archivedAt || year.archivedAt) validation('Archived students and years are read-only.'); repository.archiveStudent(db, id, now()); }
export function correctStudentGroup(db: Database.Database, teacherId: string, studentId: string, targetGroupId: string) { try { return repository.withTransaction(db, () => { const { student, group: currentGroup, year: currentYear } = ownedStudentContext(db, studentId, teacherId); const target = ownedGroup(db, targetGroupId, teacherId); const targetYear = ownedYear(db, target.academicYearId, teacherId); if (student.archivedAt || currentYear.archivedAt || targetYear.archivedAt || currentGroup.id === target.id || currentYear.id !== targetYear.id || student.groupCorrectionLockedAt) validation('Student group correction is not allowed.'); repository.moveStudent(db, student.id, target.id); return { ...student, groupId: target.id }; }); } catch (error) { return conflict(error); } }
export function lockStudentGroupCorrection(db: Database.Database, teacherId: string, studentId: string) { const { student } = ownedStudentContext(db, studentId, teacherId); repository.lockStudent(db, student.id, now()); return repository.findStudent(db, student.id)!; }
