import type Database from 'better-sqlite3';
import { randomUUID } from 'node:crypto';
import { ApiError } from '../http/errors.js';
import * as repository from './repository.js';

const fixedRewards = ['standard-assessment-advantage','exceptional-assessment-advantage'];
function ownedStudent(db:Database.Database, teacherId:string, studentId:string) { const row=db.prepare(`SELECT s.id,g.academic_year_id AS academicYearId FROM students s JOIN groups g ON g.id=s.group_id WHERE s.id=? AND g.owner_teacher_id=?`).get(studentId,teacherId) as any; if(!row)throw new ApiError('NOT_FOUND',404,'Student not found.'); return row; }
export function rewards(db:Database.Database) { return db.prepare('SELECT id,name,cost,type FROM coin_rewards WHERE id IN (?,?) ORDER BY cost').all(...fixedRewards); }
export function summary(db:Database.Database, teacherId:string, studentId:string) { const student=ownedStudent(db,teacherId,studentId); return {studentId,academicYearId:student.academicYearId,balance:repository.balance(db,studentId,student.academicYearId)}; }
export function contexts(db:Database.Database, teacherId:string, groupId:string) { return db.prepare('SELECT c.id,c.group_id AS groupId,c.name,c.archived_at AS archivedAt FROM assessment_contexts c JOIN groups g ON g.id=c.group_id WHERE c.group_id=? AND g.owner_teacher_id=? ORDER BY c.created_at,c.id').all(groupId,teacherId); }
export function createContext(db:Database.Database, teacherId:string, groupId:string, name:string) { const group=db.prepare('SELECT g.id,y.archived_at AS yearArchivedAt FROM groups g JOIN academic_years y ON y.id=g.academic_year_id WHERE g.id=? AND g.owner_teacher_id=?').get(groupId,teacherId) as any; if(!group)throw new ApiError('NOT_FOUND',404,'Group not found.'); if(group.yearArchivedAt)throw new ApiError('VALIDATION_FAILED',422,'Archived academic years are read-only.'); const canonical=name.trim(); const existing=db.prepare('SELECT id,group_id AS groupId,name,archived_at AS archivedAt FROM assessment_contexts WHERE group_id=? AND archived_at IS NULL AND lower(trim(name))=lower(trim(?)) ORDER BY created_at,id LIMIT 1').get(groupId,canonical) as any; if(existing)return {...existing,replay:true}; const id=randomUUID(); try{db.prepare('INSERT INTO assessment_contexts (id,group_id,name,created_at) VALUES (?,?,?,?)').run(id,groupId,canonical,new Date().toISOString());}catch(error){if((error as any).code!=='SQLITE_CONSTRAINT_UNIQUE')throw error; const retry=db.prepare('SELECT id,group_id AS groupId,name,archived_at AS archivedAt FROM assessment_contexts WHERE group_id=? AND archived_at IS NULL AND lower(trim(name))=lower(trim(?)) ORDER BY created_at,id LIMIT 1').get(groupId,canonical) as any;if(retry)return {...retry,replay:true};throw error;} return {id,groupId,name:canonical,archivedAt:null,replay:false}; }
export function renameContext(db:Database.Database, teacherId:string, contextId:string, name:string) { const context=db.prepare('SELECT c.id,c.group_id AS groupId,g.owner_teacher_id AS ownerTeacherId,y.archived_at AS yearArchivedAt FROM assessment_contexts c JOIN groups g ON g.id=c.group_id JOIN academic_years y ON y.id=g.academic_year_id WHERE c.id=? AND g.owner_teacher_id=?').get(contextId,teacherId) as any; if(!context)throw new ApiError('NOT_FOUND',404,'Assessment context not found.'); if(context.yearArchivedAt)throw new ApiError('VALIDATION_FAILED',422,'Archived academic years are read-only.'); const canonical=name.trim(); if(db.prepare('SELECT id FROM assessment_contexts WHERE group_id=? AND id<>? AND archived_at IS NULL AND lower(trim(name))=lower(trim(?))').get(context.groupId,contextId,canonical))throw new ApiError('CONFLICT',409,'An active assessment context already uses that name.'); db.prepare('UPDATE assessment_contexts SET name=? WHERE id=?').run(canonical,contextId); return {id:contextId,groupId:context.groupId,name:canonical,archivedAt:null}; }
