import { createHash, randomUUID } from 'node:crypto';
import type Database from 'better-sqlite3';
import { ApiError } from '../http/errors.js';
import { getOwnedAcademicYearGroupContext } from '../roster/calendar-context.js';
import { localParts, systemClock, validTimezone, type Clock } from './clock.js';
import { contains, intervalContains, intervalsOverlap, overlaps, validateTime } from './rules.js';
import * as repo from './repository.js';

export type CalendarInput = { timezone:string; terms:Array<{code:'T1'|'T2'|'T3'; startsOn:string; endsOn:string}>; holidays:Array<{startsOn:string;endsOn:string}>; slots:Array<{groupId:string;weekday:number;startsAt:string;endsAt:string}> };
const fail=(message:string, status=422):never=>{ throw new ApiError(status===404?'NOT_FOUND':status===409?'CONFLICT':'VALIDATION_FAILED',status,message); };
const now=()=>new Date().toISOString();
function year(db:Database.Database, owner:string, id:string) { const value=db.prepare('SELECT * FROM academic_years WHERE id=? AND owner_teacher_id=?').get(id,owner) as any; if(!value) fail('Academic year not found.',404); return value; }
function fingerprint(operation:string,target:string,body:unknown) { return createHash('sha256').update(JSON.stringify({operation,routeTarget:target,body})).digest('hex'); }
function validateInput(db:Database.Database, owner:string, yearId:string, input:CalendarInput) {
  const y=year(db,owner,yearId); if(y.archived_at) fail('Archived academic years are read-only.'); if(!validTimezone(input.timezone)) fail('Timezone must be a valid IANA timezone.');
  if(input.terms.length!==3 || new Set(input.terms.map(t=>t.code)).size!==3 || !['T1','T2','T3'].every(code=>input.terms.some(term=>term.code===code))) fail('Calendar requires exactly T1, T2, and T3 terms.');
  for(const t of [...input.terms,...input.holidays]) { if(t.startsOn>t.endsOn || t.startsOn<y.starts_on || t.endsOn>y.ends_on) fail('Calendar ranges must be inside the academic year.'); }
  for(let i=0;i<input.terms.length;i++) for(let j=i+1;j<input.terms.length;j++) if(overlaps(input.terms[i],input.terms[j])) fail('Terms cannot overlap.');
  for(const slot of input.slots) { if(!Number.isInteger(slot.weekday)||slot.weekday<1||slot.weekday>7||!validateTime(slot.startsAt)||!validateTime(slot.endsAt)||slot.startsAt>=slot.endsAt) fail('Timetable slots must be valid local intervals.'); getOwnedAcademicYearGroupContext(db,owner,yearId,slot.groupId); }
  for(let i=0;i<input.slots.length;i++) for(let j=i+1;j<input.slots.length;j++) if(input.slots[i].groupId===input.slots[j].groupId&&input.slots[i].weekday===input.slots[j].weekday&&intervalsOverlap(input.slots[i],input.slots[j])) fail('Timetable slots cannot overlap.');
}
export function getCalendar(db:Database.Database,owner:string,yearId:string) { const y=year(db,owner,yearId); const c=repo.findCalendar(db,yearId,owner); if(!c)return {configured:false,canReplace:!y.archived_at}; const hasHistory=!!db.prepare('SELECT 1 FROM real_class_sessions WHERE calendar_id=? LIMIT 1').get(c.id); return {configured:true,canReplace:!y.archived_at&&!hasHistory, ...c, terms:db.prepare('SELECT id,code,starts_on startsOn,ends_on endsOn FROM academic_terms WHERE calendar_id=? ORDER BY code').all(c.id), holidays:db.prepare('SELECT id,starts_on startsOn,ends_on endsOn FROM calendar_holidays WHERE calendar_id=?').all(c.id), slots:db.prepare('SELECT id,group_id groupId,weekday,starts_at startsAt,ends_at endsAt FROM weekly_timetable_slots WHERE calendar_id=?').all(c.id)}; }
export function replaceCalendar(db:Database.Database,owner:string,yearId:string,input:CalendarInput) { return repo.withTransaction(db,()=>{ validateInput(db,owner,yearId,input); const existing=repo.findCalendar(db,yearId,owner); if(existing&&db.prepare('SELECT 1 FROM real_class_sessions WHERE calendar_id=? LIMIT 1').get(existing.id)) fail('Calendar cannot be edited after the first session.',409); const c=existing??{id:randomUUID(),academicYearId:yearId,ownerTeacherId:owner,createdAt:now()}; const stamp=now(); if(existing) { db.prepare('UPDATE academic_calendars SET timezone=?,updated_at=? WHERE id=?').run(input.timezone,stamp,existing.id); db.prepare('DELETE FROM academic_terms WHERE calendar_id=?').run(existing.id); db.prepare('DELETE FROM calendar_holidays WHERE calendar_id=?').run(existing.id); db.prepare('DELETE FROM weekly_timetable_slots WHERE calendar_id=?').run(existing.id); } else db.prepare('INSERT INTO academic_calendars VALUES (?,?,?,?,?,?)').run(c.id,yearId,owner,input.timezone,c.createdAt,stamp); for(const t of input.terms) db.prepare('INSERT INTO academic_terms VALUES (?,?,?,?,?,?,?)').run(randomUUID(),c.id,yearId,owner,t.code,t.startsOn,t.endsOn); for(const h of input.holidays) db.prepare('INSERT INTO calendar_holidays VALUES (?,?,?,?,?,?)').run(randomUUID(),c.id,yearId,owner,h.startsOn,h.endsOn); for(const s of input.slots) db.prepare('INSERT INTO weekly_timetable_slots VALUES (?,?,?,?,?,?,?,?)').run(randomUUID(),c.id,yearId,owner,s.groupId,s.weekday,s.startsAt,s.endsAt); return getCalendar(db,owner,yearId); }); }
function requestReplay(db:Database.Database,owner:string,key:string,op:string,target:string,body:unknown) { const r=db.prepare('SELECT * FROM real_class_session_requests WHERE owner_teacher_id=? AND idempotency_key=?').get(owner,key) as any; if(!r)return; const fp=fingerprint(op,target,body); if(r.operation!==op||r.fingerprint!==fp) fail('Idempotency key was already used for another request.',409); return { replay:true, session:db.prepare('SELECT * FROM real_class_sessions WHERE id=?').get(r.session_id) as any }; }
function eligible(db:Database.Database,owner:string,yearId:string,groupId:string,clock:Clock) { const c=repo.findChain(db,owner,yearId,groupId); if(!c)return null; const archived=db.prepare('SELECT archived_at FROM academic_years WHERE id=? AND owner_teacher_id=?').get(yearId,owner) as { archived_at:string|null }|undefined; if(archived?.archived_at)return null; const p=localParts(clock.now(),c.timezone); const term=db.prepare('SELECT * FROM academic_terms WHERE calendar_id=? AND starts_on<=? AND ends_on>=?').get(c.id,p.date,p.date) as any; const holiday=db.prepare('SELECT 1 FROM calendar_holidays WHERE calendar_id=? AND starts_on<=? AND ends_on>=?').get(c.id,p.date,p.date); const slot=db.prepare('SELECT * FROM weekly_timetable_slots WHERE calendar_id=? AND group_id=? AND weekday=? AND starts_at<=? AND ends_at>?').get(c.id,groupId,p.weekday,p.time,p.time) as any; return {c,p,term,holiday,slot}; }
export function status(db:Database.Database,owner:string,yearId:string,groupId:string,clock=systemClock) { const y=year(db,owner,yearId); getOwnedAcademicYearGroupContext(db,owner,yearId,groupId); const calendar=repo.findCalendar(db,yearId,owner); const e=eligible(db,owner,yearId,groupId,clock); const active=db.prepare('SELECT * FROM real_class_sessions WHERE owner_teacher_id=? AND ended_at IS NULL').get(owner) as any; const prior=!!e?.slot&&!!db.prepare('SELECT 1 FROM real_class_sessions WHERE slot_id=? AND local_date=?').get(e.slot.id,e.p.date); let reason:'ACTIVE_SESSION'|'UNCONFIGURED'|'OUTSIDE_TERM'|'HOLIDAY'|'OUTSIDE_TIMETABLE'|'USED_SLOT_DATE'|'ELIGIBLE'; if(active) reason='ACTIVE_SESSION'; else if(!calendar) reason='UNCONFIGURED'; else if(!e?.term) reason='OUTSIDE_TERM'; else if(e.holiday) reason='HOLIDAY'; else if(!e.slot) reason='OUTSIDE_TIMETABLE'; else if(prior) reason='USED_SLOT_DATE'; else reason='ELIGIBLE'; return {configured:!!calendar, canReplace:!!calendar&&!y.archived_at&&!db.prepare('SELECT 1 FROM real_class_sessions WHERE calendar_id=? LIMIT 1').get(calendar.id), eligible:reason==='ELIGIBLE', reason, active:active?mapSession(active):null}; }
function mapSession(s:any){return {id:s.id,academicYearId:s.academic_year_id,groupId:s.group_id,localDate:s.local_date,timezone:s.timezone,slotStartsAt:s.slot_starts_at,slotEndsAt:s.slot_ends_at,startedAt:s.started_at,endedAt:s.ended_at,createdAt:s.created_at};}
/** Narrow downstream seam: exposes only an owned, lineage-verified real session. */
 export function getOwnedRealClassSessionContext(db:Database.Database,owner:string,sessionId:string) { const row=db.prepare(`SELECT s.* FROM real_class_sessions s JOIN academic_calendars c ON c.id=s.calendar_id AND c.academic_year_id=s.academic_year_id AND c.owner_teacher_id=s.owner_teacher_id JOIN academic_terms t ON t.id=s.term_id AND t.calendar_id=s.calendar_id AND t.academic_year_id=s.academic_year_id AND t.owner_teacher_id=s.owner_teacher_id JOIN weekly_timetable_slots slot ON slot.id=s.slot_id AND slot.calendar_id=s.calendar_id AND slot.academic_year_id=s.academic_year_id AND slot.owner_teacher_id=s.owner_teacher_id AND slot.group_id=s.group_id JOIN groups g ON g.id=s.group_id AND g.academic_year_id=s.academic_year_id AND g.owner_teacher_id=s.owner_teacher_id WHERE s.id=? AND s.owner_teacher_id=?`).get(sessionId,owner) as any; if(!row) fail('Real class session not found.',404); return {...mapSession(row), ownerTeacherId:row.owner_teacher_id, termId:row.term_id}; }
export function start(db:Database.Database,owner:string,yearId:string,groupId:string,key:string,clock=systemClock) { if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(key)) fail('Idempotency-Key must be a UUID-v4.'); getOwnedAcademicYearGroupContext(db,owner,yearId,groupId); const body={academicYearId:yearId}; const replay=requestReplay(db,owner,key,'START',groupId,body); if(replay)return {status:200,session:mapSession(replay.session)}; return repo.withTransaction(db,()=>{const again=requestReplay(db,owner,key,'START',groupId,body);if(again)return {status:200,session:mapSession(again.session)};const e=eligible(db,owner,yearId,groupId,clock) ?? fail('No class is eligible at this time.');if(!e.term||e.holiday||!e.slot)fail('No class is eligible at this time.');if(db.prepare('SELECT 1 FROM real_class_sessions WHERE owner_teacher_id=? AND ended_at IS NULL').get(owner))fail('A class session is already active.',409);if(db.prepare('SELECT 1 FROM real_class_sessions WHERE slot_id=? AND local_date=?').get(e.slot.id,e.p.date))fail('This slot already has a session for this date.',409);const id=randomUUID(),stamp=now();db.prepare('INSERT INTO real_class_sessions VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,owner,yearId,groupId,e.c.id,e.term.id,e.slot.id,e.p.date,e.c.timezone,e.slot.starts_at,e.slot.ends_at,clock.now().toISOString(),null,stamp);db.prepare('INSERT INTO real_class_session_requests VALUES (?,?,?,?,?,?,?)').run(randomUUID(),owner,key,'START',fingerprint('START',groupId,body),id,stamp);return {status:201,session:mapSession(db.prepare('SELECT * FROM real_class_sessions WHERE id=?').get(id))};}); }
export function end(db:Database.Database,owner:string,sessionId:string,key:string,clock=systemClock) { if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(key)) fail('Idempotency-Key must be a UUID-v4.'); const body={}; const replay=requestReplay(db,owner,key,'END',sessionId,body);if(replay)return {status:200,session:mapSession(replay.session)}; return repo.withTransaction(db,()=>{const again=requestReplay(db,owner,key,'END',sessionId,body);if(again)return {status:200,session:mapSession(again.session)};const s=db.prepare('SELECT * FROM real_class_sessions WHERE id=? AND owner_teacher_id=?').get(sessionId,owner) as any;if(!s)fail('Real class session not found.',404);if(s.ended_at)fail('Session is already closed.',409);const ended=clock.now().toISOString();db.prepare('UPDATE real_class_sessions SET ended_at=? WHERE id=? AND ended_at IS NULL').run(ended,sessionId);db.prepare('INSERT INTO real_class_session_requests VALUES (?,?,?,?,?,?,?)').run(randomUUID(),owner,key,'END',fingerprint('END',sessionId,body),sessionId,now());return {status:201,session:mapSession({...s,ended_at:ended})};}); }
export function assertAcademicYearLifecycleChange(db:Database.Database,yearId:string,startsOn:string,endsOn:string){const bad=db.prepare(`SELECT 1 FROM academic_terms WHERE academic_year_id=? AND (starts_on<? OR ends_on>?) UNION SELECT 1 FROM calendar_holidays WHERE academic_year_id=? AND (starts_on<? OR ends_on>?) UNION SELECT 1 FROM real_class_sessions WHERE academic_year_id=? AND (local_date<? OR local_date>?) LIMIT 1`).get(yearId,startsOn,endsOn,yearId,startsOn,endsOn,yearId,startsOn,endsOn);if(bad)fail('Academic year range excludes configured calendar data or session history.',422);}
export function assertArchiveAllowed(db:Database.Database,yearId:string){if(db.prepare('SELECT 1 FROM real_class_sessions WHERE academic_year_id=? AND ended_at IS NULL').get(yearId))fail('Active sessions must be closed before archiving.',409);}
