import { randomUUID } from 'node:crypto';
import type Database from 'better-sqlite3';
import { rubricCategories, calculateRubricCategory, rubricGradeMilli, type RubricLevel, type RubricState } from '@eclipse/domain';

export type RubricCategory = typeof rubricCategories[number];
export type RubricEvaluation = { id:string; studentId:string; termId:string; calendarId:string; ownerTeacherId:string; academicYearId:string; groupId:string; state:RubricState; revision:number; overrides:Record<RubricCategory,RubricLevel|null>; draftComment:string|null; currentSnapshotVersion:number|null; archived:boolean };
export type Aggregate = { category:RubricCategory; baseXp:number; qualifyingEventCount:number; suggestedLevel:RubricLevel; overrideLevel:RubricLevel|null; finalLevel:RubricLevel; lowEvidence:boolean; eventIds:string[] };

const cols = `communication_override AS communicationOverride, precision_override AS precisionOverride, consistency_override AS consistencyOverride, collaboration_override AS collaborationOverride`;
const mapEvaluation = (row:any):RubricEvaluation => ({ id:row.id, studentId:row.studentId, termId:row.termId, calendarId:row.calendarId, ownerTeacherId:row.ownerTeacherId, academicYearId:row.academicYearId, groupId:row.groupId, state:row.state, revision:row.revision, overrides:{ COMMUNICATION:row.communicationOverride, PRECISION:row.precisionOverride, CONSISTENCY:row.consistencyOverride, COLLABORATION:row.collaborationOverride }, draftComment:row.draftComment, currentSnapshotVersion:row.currentSnapshotVersion, archived:Boolean(row.archived) });
export function withImmediateTransaction<T>(db:Database.Database, work:()=>T):T { return db.transaction(work).immediate(); }

export function ownedLineage(db:Database.Database, teacherId:string, studentId:string, termId:string, yearId:string) {
  return db.prepare(`SELECT s.id AS studentId,s.archived_at AS studentArchived,g.id AS groupId,g.owner_teacher_id AS ownerTeacherId,y.id AS academicYearId,y.archived_at AS yearArchived,t.id AS termId,t.calendar_id AS calendarId FROM students s JOIN groups g ON g.id=s.group_id JOIN academic_years y ON y.id=g.academic_year_id JOIN academic_terms t ON t.id=? AND t.academic_year_id=y.id AND t.owner_teacher_id=y.owner_teacher_id WHERE s.id=? AND y.id=? AND y.owner_teacher_id=?`).get(termId,studentId,yearId,teacherId) as any;
}
export function ownedGroupLineage(db:Database.Database, teacherId:string, groupId:string, termId:string, yearId:string) { return db.prepare(`SELECT g.id AS groupId,y.id AS academicYearId,t.id AS termId,t.calendar_id AS calendarId,y.archived_at AS yearArchived FROM groups g JOIN academic_years y ON y.id=g.academic_year_id JOIN academic_terms t ON t.id=? AND t.academic_year_id=y.id AND t.owner_teacher_id=y.owner_teacher_id WHERE g.id=? AND y.id=? AND y.owner_teacher_id=?`).get(termId,groupId,yearId,teacherId) as any; }
export function findEvaluation(db:Database.Database, studentId:string, termId:string) { const row=db.prepare(`SELECT e.id AS id,e.student_id AS studentId,e.term_id AS termId,e.calendar_id AS calendarId,e.owner_teacher_id AS ownerTeacherId,e.academic_year_id AS academicYearId,e.group_id AS groupId,e.state AS state,e.revision AS revision,e.communication_override AS communicationOverride,e.precision_override AS precisionOverride,e.consistency_override AS consistencyOverride,e.collaboration_override AS collaborationOverride,e.draft_comment AS draftComment,e.current_snapshot_version AS currentSnapshotVersion,e.created_at AS created,e.updated_at AS updated,(s.archived_at IS NOT NULL OR y.archived_at IS NOT NULL) AS archived FROM observation_rubric_evaluations e JOIN students s ON s.id=e.student_id JOIN groups g ON g.id=s.group_id JOIN academic_years y ON y.id=g.academic_year_id WHERE e.student_id=? AND e.term_id=?`).get(studentId,termId) as any; return row?mapEvaluation(row):null; }
export function ensureEvaluation(db:Database.Database, lineage:any):RubricEvaluation { const existing=findEvaluation(db,lineage.studentId,lineage.termId); if(existing)return existing; const id=randomUUID(), time=new Date().toISOString(); db.prepare(`INSERT INTO observation_rubric_evaluations (id,student_id,term_id,calendar_id,owner_teacher_id,academic_year_id,group_id,state,revision,draft_comment,created_at,updated_at) VALUES (?,?,?,?,?,?,?, 'OPEN',0,NULL,?,?)`).run(id,lineage.studentId,lineage.termId,lineage.calendarId,lineage.ownerTeacherId,lineage.academicYearId,lineage.groupId,time,time); return findEvaluation(db,lineage.studentId,lineage.termId)!; }
export function aggregates(db:Database.Database, studentId:string, yearId:string, termId:string, overrides:Record<RubricCategory,RubricLevel|null>) {
  const rows=db.prepare(`SELECT e.id,e.category,e.base_xp AS baseXp FROM xp_evidence_events e LEFT JOIN xp_evidence_reversals r ON r.target_event_id=e.id WHERE e.student_id=? AND e.academic_year_id=? AND e.term_id=? AND r.id IS NULL ORDER BY e.id`).all(studentId,yearId,termId) as any[];
  return rubricCategories.map(category=>{const values=rows.filter(r=>r.category===category); const result=calculateRubricCategory(values.map(r=>r.baseXp),overrides[category]); return {category,...result,eventIds:values.map(r=>r.id)};});
}
export function unattributedCount(db:Database.Database, studentId:string, yearId:string) { return (db.prepare(`SELECT COUNT(*) AS count FROM xp_evidence_events e LEFT JOIN xp_evidence_reversals r ON r.target_event_id=e.id WHERE e.student_id=? AND e.academic_year_id=? AND e.term_id IS NULL AND r.id IS NULL`).get(studentId,yearId) as any).count as number; }
export function snapshot(db:Database.Database,evaluation:RubricEvaluation, rows:Aggregate[], comment:string|null, teacherId:string) { const version=(evaluation.currentSnapshotVersion??0)+1; const levels=rows.map(r=>r.finalLevel); const id=randomUUID(), time=new Date().toISOString(); db.prepare(`INSERT INTO observation_rubric_snapshots (id,evaluation_id,version,communication_suggested,precision_suggested,consistency_suggested,collaboration_suggested,communication_final,precision_final,consistency_final,collaboration_final,communication_base_xp,precision_base_xp,consistency_base_xp,collaboration_base_xp,communication_event_count,precision_event_count,consistency_event_count,collaboration_event_count,has_low_evidence,level_sum,grade_milli,comment,closed_at,closed_by_teacher_id,prior_version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,evaluation.id,version,...rows.map(r=>r.suggestedLevel),...levels,...rows.map(r=>r.baseXp),...rows.map(r=>r.qualifyingEventCount),rows.some(r=>r.lowEvidence)?1:0,levels.reduce((a,b)=>a+b,0),rubricGradeMilli(levels),comment,time,teacherId,evaluation.currentSnapshotVersion); for(const row of rows) for(const eventId of row.eventIds) db.prepare('INSERT INTO observation_rubric_snapshot_evidence (snapshot_id,xp_event_id,category,base_xp) VALUES (?,?,?,?)').run(id,eventId,row.category,(db.prepare('SELECT base_xp FROM xp_evidence_events WHERE id=?').get(eventId) as any).base_xp); return {version,id}; }
export function updateEvaluation(db:Database.Database,e:RubricEvaluation, values:any) { db.prepare(`UPDATE observation_rubric_evaluations SET state=?,revision=?,communication_override=?,precision_override=?,consistency_override=?,collaboration_override=?,draft_comment=?,current_snapshot_version=?,updated_at=? WHERE id=?`).run(values.state??e.state,values.revision??e.revision,values.overrides?.COMMUNICATION??null,values.overrides?.PRECISION??null,values.overrides?.CONSISTENCY??null,values.overrides?.COLLABORATION??null,values.draftComment??null,values.currentSnapshotVersion??e.currentSnapshotVersion,new Date().toISOString(),e.id); }
export function request(db:Database.Database,teacherId:string,key:string) { return db.prepare('SELECT * FROM observation_rubric_requests WHERE owner_teacher_id=? AND idempotency_key=?').get(teacherId,key) as any; }
export function recordRequest(db:Database.Database, input:any) { db.prepare(`INSERT INTO observation_rubric_requests (id,owner_teacher_id,idempotency_key,operation,fingerprint,evaluation_id,resulting_revision,snapshot_version,created_at) VALUES (?,?,?,?,?,?,?,?,?)`).run(randomUUID(),input.teacherId,input.key,input.operation,input.fingerprint,input.evaluationId,input.revision,input.version??null,new Date().toISOString()); }
export function recordLifecycle(db:Database.Database,e:RubricEvaluation,operation:string,revision:number,state:string,version:number|null,reason:string|null,teacherId:string) { db.prepare(`INSERT INTO observation_rubric_lifecycle_events (id,evaluation_id,operation,resulting_revision,resulting_state,snapshot_version,reason,actor_teacher_id,occurred_at) VALUES (?,?,?,?,?,?,?,?,?)`).run(randomUUID(),e.id,operation,revision,state,version,reason,teacherId,new Date().toISOString()); }
export function latestSnapshot(db:Database.Database,evaluationId:string,version:number|null) { return version===null?null:db.prepare('SELECT * FROM observation_rubric_snapshots WHERE evaluation_id=? AND version=?').get(evaluationId,version) as any; }
export function groupRows(db:Database.Database,groupId:string,yearId:string,termId:string) { return db.prepare(`SELECT s.id AS studentId,s.alias,s.archived_at AS studentArchived,e.state,e.revision,e.current_snapshot_version AS version,ss.grade_milli AS gradeMilli,ss.has_low_evidence AS hasLowEvidence FROM students s LEFT JOIN observation_rubric_evaluations e ON e.student_id=s.id AND e.term_id=? LEFT JOIN observation_rubric_snapshots ss ON ss.evaluation_id=e.id AND ss.version=e.current_snapshot_version WHERE s.group_id=? ORDER BY s.alias COLLATE NOCASE,s.id`).all(termId,groupId) as any[]; }
