import { createHash } from 'node:crypto';
import type Database from 'better-sqlite3';
import { ApiError } from '../http/errors.js';
import { rubricCategories, formatGrade, type RubricLevel } from '@eclipse/domain';
import * as repo from './repository.js';

const uuidV4=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const keyOf=(key:string|undefined)=>{if(!key||!uuidV4.test(key))throw new ApiError('VALIDATION_FAILED',422,'A UUID v4 Idempotency-Key header is required.');return key;};
const fp=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
function context(db:Database.Database,teacherId:string,studentId:string,termId:string,yearId:string){const value=repo.ownedLineage(db,teacherId,studentId,termId,yearId);if(!value)throw new ApiError('NOT_FOUND',404,'Observation rubric not found.');return value;}
function checkExpected(e:repo.RubricEvaluation, expected:number){if(e.revision!==expected)throw new ApiError('CONFLICT',409,'The rubric revision is stale.');}
function bodyOverrides(value:any):Record<any, RubricLevel|null>{return Object.fromEntries(rubricCategories.map(c=>[c,value.overrides[c]??null])) as any;}
export function read(db:Database.Database,teacherId:string,studentId:string,termId:string,yearId:string){
  const line=context(db,teacherId,studentId,termId,yearId),e=repo.findEvaluation(db,studentId,termId)??{id:'',studentId,termId,ownerTeacherId:teacherId,academicYearId:yearId,groupId:line.groupId,state:'OPEN' as const,revision:0,overrides:Object.fromEntries(rubricCategories.map(c=>[c,null])) as any,draftComment:null,currentSnapshotVersion:null,archived:Boolean(line.studentArchived||line.yearArchived)};
  const liveCategories=repo.aggregates(db,studentId,yearId,termId,e.overrides);
  const official=repo.latestSnapshot(db,e.id,e.currentSnapshotVersion);
  const currentIds=liveCategories.flatMap(c=>c.eventIds);
  const snapshotIds=official?db.prepare('SELECT xp_event_id AS id FROM observation_rubric_snapshot_evidence WHERE snapshot_id=?').all(official.id).map((r:any)=>r.id):[];
  const categories=e.state==='CLOSED'&&official?rubricCategories.map(category=>{const name=category.toLowerCase();return {category,baseXp:official[`${name}_base_xp`],qualifyingEventCount:official[`${name}_event_count`],suggestedLevel:official[`${name}_suggested`],overrideLevel:official[`${name}_final`],finalLevel:official[`${name}_final`],lowEvidence:official[`${name}_event_count`]<4};}):liveCategories.map(({eventIds,...x})=>x);
  return {studentId,academicYearId:yearId,termId,state:e.state,revision:e.revision,archived:e.archived,draftComment:e.draftComment,categories,snapshot:official?{version:official.version,gradeMilli:official.grade_milli,gradeDecimal:formatGrade(official.grade_milli),comment:official.comment,closedAt:official.closed_at,closedByTeacherId:official.closed_by_teacher_id,priorVersion:official.prior_version}:null,stale:official?currentIds.length!==snapshotIds.length||currentIds.some(id=>!snapshotIds.includes(id)):false,unattributedAnnualEventCount:repo.unattributedCount(db,studentId,yearId)};
}
export type RubricMutationValue = ReturnType<typeof read>;
type MutationResult = { value: RubricMutationValue; revision?: number; version?: number|null };
type MutationResponse = { status: 200|201; value: RubricMutationValue };
function mutation(db:Database.Database,teacherId:string,studentId:string,termId:string,yearId:string,key:string,operation:string,body:any,action:(e:repo.RubricEvaluation,line:any)=>MutationResult):MutationResponse {const idempotency=keyOf(key), fingerprint=fp({operation,studentId,termId,yearId,body});return repo.withImmediateTransaction(db,()=>{const prior=repo.request(db,teacherId,idempotency);if(prior){if(prior.fingerprint!==fingerprint)throw new ApiError('CONFLICT',409,'Idempotency-Key was already used for a different request.');return {status:200,value:read(db,teacherId,studentId,termId,yearId)};}const line=context(db,teacherId,studentId,termId,yearId);const e=repo.ensureEvaluation(db,line);const result=action(e,line);repo.recordRequest(db,{teacherId,key:idempotency,operation,fingerprint,evaluationId:e.id,revision:result.revision??repo.findEvaluation(db,studentId,termId)!.revision,version:result.version});return {status:201,value:result.value};});}
export function save(db:Database.Database,teacherId:string,studentId:string,termId:string,yearId:string,key:string,input:any){return mutation(db,teacherId,studentId,termId,yearId,key,'SAVE',input,(e,line)=>{if(e.archived)throw new ApiError('VALIDATION_FAILED',422,'Archived records are read-only.');if(e.state==='CLOSED')throw new ApiError('VALIDATION_FAILED',422,'Closed rubrics are read-only.');checkExpected(e,input.expectedRevision);const overrides=bodyOverrides(input);repo.updateEvaluation(db,e,{revision:e.revision+1,overrides,draftComment:input.comment?.trim()||null});return {value:read(db,teacherId,studentId,termId,yearId),revision:e.revision+1};});}
export function close(db:Database.Database,teacherId:string,studentId:string,termId:string,yearId:string,key:string,input:any){return mutation(db,teacherId,studentId,termId,yearId,key,'CLOSE',input,(e,line)=>{if(e.archived)throw new ApiError('VALIDATION_FAILED',422,'Archived records are read-only.');if(e.state==='CLOSED')throw new ApiError('CONFLICT',409,'Rubric is already closed.');checkExpected(e,input.expectedRevision);const rows=repo.aggregates(db,studentId,yearId,termId,e.overrides);const snap=repo.snapshot(db,e,rows,e.draftComment,teacherId);repo.updateEvaluation(db,e,{state:'CLOSED',revision:e.revision+1,currentSnapshotVersion:snap.version});repo.recordLifecycle(db,e,'CLOSE',e.revision+1,'CLOSED',snap.version,null,teacherId);return {value:read(db,teacherId,studentId,termId,yearId),revision:e.revision+1,version:snap.version};});}
export function reopen(db:Database.Database,teacherId:string,studentId:string,termId:string,yearId:string,key:string,input:any){return mutation(db,teacherId,studentId,termId,yearId,key,'REOPEN',input,(e)=>{if(e.archived)throw new ApiError('VALIDATION_FAILED',422,'Archived records are read-only.');if(e.state!=='CLOSED')throw new ApiError('CONFLICT',409,'Only closed rubrics can be reopened.');checkExpected(e,input.expectedRevision);const snap=repo.latestSnapshot(db,e.id,e.currentSnapshotVersion)!;const overrides={COMMUNICATION:snap.communication_final,PRECISION:snap.precision_final,CONSISTENCY:snap.consistency_final,COLLABORATION:snap.collaboration_final};repo.updateEvaluation(db,e,{state:'REOPENED',revision:e.revision+1,overrides,draftComment:snap.comment});repo.recordLifecycle(db,e,'REOPEN',e.revision+1,'REOPENED',e.currentSnapshotVersion,input.reason.trim(),teacherId);return {value:read(db,teacherId,studentId,termId,yearId),revision:e.revision+1,version:e.currentSnapshotVersion};});}
export function group(db:Database.Database,teacherId:string,groupId:string,termId:string,yearId:string){if(!repo.ownedGroupLineage(db,teacherId,groupId,termId,yearId))throw new ApiError('NOT_FOUND',404,'Observation rubrics not found.');return {groupId,academicYearId:yearId,termId,students:repo.groupRows(db,groupId,yearId,termId).map(row=>({studentId:row.studentId,state:row.state??'OPEN',revision:row.revision??0,hasLowEvidence:Boolean(row.hasLowEvidence??true),latestSnapshot:row.version?{version:row.version,gradeDecimal:formatGrade(row.gradeMilli)}:null}))};}
