import { afterEach, describe, expect, it } from 'vitest';
import Database from 'better-sqlite3';
import { migrateDatabase } from '../db/migrate.js';
import { migrations } from '../db/migrations.js';
import * as service from './service.js';

const dbs: Database.Database[] = [];
afterEach(() => { for (const db of dbs.splice(0)) db.close(); });
const ids = { teacher:'00000000-0000-4000-8000-000000000001', year:'00000000-0000-4000-8000-000000000002', group:'00000000-0000-4000-8000-000000000003', student:'00000000-0000-4000-8000-000000000004', student2:'00000000-0000-4000-8000-000000000005' };
function database() { const db=new Database(':memory:'); db.pragma('foreign_keys=ON'); migrateDatabase(db,migrations); db.prepare('INSERT INTO teacher_accounts (id,email,password_hash,created_at) VALUES (?,?,?,?)').run(ids.teacher,'teacher@example.test','hash','now'); db.prepare('INSERT INTO academic_years (id,owner_teacher_id,label,starts_on,ends_on,created_at) VALUES (?,?,?,?,?,?)').run(ids.year,ids.teacher,'2026','2026-09-01','2027-07-01','now'); db.prepare('INSERT INTO groups (id,owner_teacher_id,academic_year_id,name,created_at) VALUES (?,?,?,?,?)').run(ids.group,ids.teacher,ids.year,'A','now'); db.prepare('INSERT INTO students (id,group_id,real_name,alias,avatar,specialty,created_at) VALUES (?,?,?,?,?,?,?)').run(ids.student,ids.group,'Ada','A','default','Leader','now'); dbs.push(db); return db; }
const key=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
describe('XP repository transaction behavior', () => {
  it('derives active totals and creates one threshold grant', () => { const db=database(); const first=service.create(db,ids.teacher,ids.student,{category:'COMMUNICATION',baseXp:3},key(10)); expect(first.summary.annualEffectiveXp).toBe(4); for(let i=0;i<2;i++)service.create(db,ids.teacher,ids.student,{category:'COMMUNICATION',baseXp:3},key(11+i)); expect(service.create(db,ids.teacher,ids.student,{category:'COMMUNICATION',baseXp:3},key(20)).summary.badges).toHaveLength(1); expect((db.prepare("SELECT COUNT(*) AS count FROM xp_level_grant_transitions WHERE kind='GRANT'").get() as any).count).toBe(1); });
  it('reverses immutably and replays the same idempotency key', () => { const db=database(); const created=service.create(db,ids.teacher,ids.student,{category:'PRECISION',baseXp:2},key(30)); const reversed=service.reverse(db,ids.teacher,created.event.id,{},key(31)); expect(reversed.summary.annualEffectiveXp).toBe(0); const replay=service.reverse(db,ids.teacher,created.event.id,{},key(31)); expect(replay.replay).toBe(true); expect(db.prepare('SELECT COUNT(*) AS count FROM xp_evidence_events').get()).toEqual({count:1}); expect(db.prepare('SELECT COUNT(*) AS count FROM xp_evidence_reversals').get()).toEqual({count:1}); });
  it('returns zero-XP roster rows in one bounded summary read ordered by alias', () => { const db=database(); db.prepare('INSERT INTO students (id,group_id,real_name,alias,avatar,specialty,created_at) VALUES (?,?,?,?,?,?,?)').run(ids.student2,ids.group,'Bea','Z','default',null,'now'); service.create(db,ids.teacher,ids.student,{category:'PRECISION',baseXp:1},key(40)); const rows=service.groupSummaries(db,ids.teacher,ids.group,ids.year); expect(rows.summaries.map(row=>[row.studentId,row.summary.annualEffectiveXp])).toEqual([[ids.student,1],[ids.student2,0]]); expect(rows.summaries).toHaveLength(2); });
  it('replays a timeout key without creating another event and rejects a fingerprint conflict', () => { const db=database(); const first=service.create(db,ids.teacher,ids.student,{category:'PRECISION',baseXp:1},key(50)); const replay=service.create(db,ids.teacher,ids.student,{category:'PRECISION',baseXp:1},key(50)); expect(replay.replay).toBe(true); expect(replay.event.id).toBe(first.event.id); expect(() => service.create(db,ids.teacher,ids.student,{category:'PRECISION',baseXp:2},key(50))).toThrowError(/different request/); expect((db.prepare('SELECT COUNT(*) AS count FROM xp_evidence_events').get() as any).count).toBe(1); });
  it('appends REVOKE on a threshold fall and REINSTATE on regain', () => { const db=database(); const created=[1,2,3].map(n=>service.create(db,ids.teacher,ids.student,{category:'COMMUNICATION',baseXp:3},key(60+n))); const reversed=service.reverse(db,ids.teacher,created[0].event.id,{},key(70)); expect(reversed.summary.annualEffectiveXp).toBe(8); service.create(db,ids.teacher,ids.student,{category:'COMMUNICATION',baseXp:3},key(71)); expect((db.prepare("SELECT kind FROM xp_level_grant_transitions ORDER BY sequence").all() as {kind:string}[]).map(row=>row.kind)).toEqual(['GRANT','REVOKE','REINSTATE']); });
});
