import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import type Database from 'better-sqlite3';
import { requireSession } from '../auth/routes.js';
import { ApiError } from '../http/errors.js';
import { validateBody } from '../http/validation.js';
import { xpCreateBodySchema, xpReverseBodySchema } from '@eclipse/contracts';
import * as service from './service.js';
const uuid=z.string().uuid(); const teacher=(r:FastifyRequest)=>(r as FastifyRequest&{teacherId:string}).teacherId; const id=(r:FastifyRequest,key='id')=>uuid.parse((r.params as Record<string,string>)[key]);
function cursor(value: unknown) { if(value===undefined||value==='') return null; try { const decoded=JSON.parse(Buffer.from(String(value),'base64url').toString('utf8')); if(decoded.v!==1||!uuid.safeParse(decoded.id).success||typeof decoded.createdAt!=='string') throw new Error(); return {createdAt:decoded.createdAt,id:decoded.id}; } catch { throw new ApiError('VALIDATION_FAILED',422,'Cursor is invalid.'); } }
export function registerXpRoutes(app: FastifyInstance, db: Database.Database) { const session=requireSession(db); app.post('/api/v1/students/:studentId/xp-evidence',{preHandler:[session,validateBody(xpCreateBodySchema)]},async(r,reply)=>{const input=xpCreateBodySchema.parse(r.body);const result=service.create(db,teacher(r),id(r,'studentId'),input,r.headers['idempotency-key'] as string);return reply.code(result.replay?200:201).send({event:result.event,summary:result.summary});}); app.post('/api/v1/xp-evidence/:eventId/reversal',{preHandler:[session,validateBody(xpReverseBodySchema)]},async(r,reply)=>{const result=service.reverse(db,teacher(r),id(r,'eventId'),xpReverseBodySchema.parse(r.body),r.headers['idempotency-key'] as string);return reply.code(result.replay?200:201).send(result);}); app.get('/api/v1/students/:studentId/xp-summary',{preHandler:session},async(r)=>{const query=z.object({academicYearId:uuid}).parse(r.query);return service.getSummary(db,teacher(r),id(r,'studentId'),query.academicYearId);}); app.get('/api/v1/groups/:groupId/xp-summaries',{preHandler:session},async(r)=>{const query=z.object({academicYearId:uuid}).parse(r.query);return service.groupSummaries(db,teacher(r),id(r,'groupId'),query.academicYearId);}); app.get('/api/v1/students/:studentId/xp-evidence',{preHandler:session},async(r)=>{const query=z.object({academicYearId:uuid,cursor:z.string().optional(),limit:z.coerce.number().int().min(1).max(50).default(25)}).parse(r.query);const result=service.listEvidence(db,teacher(r),id(r,'studentId'),query.academicYearId,cursor(query.cursor),query.limit);return {items:result.items,nextCursor:result.nextCursor?Buffer.from(JSON.stringify({v:1,...result.nextCursor})).toString('base64url'):null};}); }
