import { randomUUID } from 'node:crypto';
import type Database from 'better-sqlite3';
import { ApiError } from '../http/errors.js';
import * as roster from '../roster/service.js';
import * as repository from './repository.js';
import { specialtyCategory, type Specialty } from './service-types.js';
import type { XpBonusEligibilityPort } from './bonus-eligibility.js';
import { runImmediateTransaction, type GemSourceTx } from '../services/transactions.js';
import type { GemSourceOrchestrator } from '../gems/source-orchestrator.js';
const now = () => new Date().toISOString();
const validCategories = ['COMMUNICATION','PRECISION','CONSISTENCY','COLLABORATION'] as const;
export type XpCategory = typeof validCategories[number];
export function categoryForSpecialty(specialty: string|null) { return specialty && specialty in specialtyCategory ? specialtyCategory[specialty as Specialty] : null; }
function checkKey(key: string|undefined): string { if (!key || !/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(key)) throw new ApiError('VALIDATION_FAILED',422,'A UUID v4 Idempotency-Key header is required.'); return key; }
function writable(context: ReturnType<typeof roster.getOwnedStudentAcademicYearContext>) { if (context.student.archivedAt || context.year.archivedAt) throw new ApiError('VALIDATION_FAILED',422,'Archived students and academic years are read-only.'); return context; }
function transitionIds(db: Database.Database, column: 'source_event_id'|'source_reversal_id', id: string) {
  const opposite = column === 'source_event_id' ? 'source_reversal_id' : 'source_event_id';
  const rows = db.prepare(`SELECT id,${column} AS sourceId,${opposite} AS oppositeSourceId FROM xp_level_grant_transitions WHERE ${column}=? ORDER BY sequence`).all(id) as Array<{id:string;sourceId:string;oppositeSourceId:string|null}>;
  if (rows.some(row => row.sourceId !== id || row.oppositeSourceId !== null)) throw new ApiError('CONFLICT',409,'XP transition source lineage is inconsistent.');
  return rows.map(row=>row.id);
}
export function create(db: Database.Database, teacherId: string, studentId: string, input: { category: XpCategory; baseXp: 1|2|3; comment?: string }, key: string, eligibility: XpBonusEligibilityPort = { specialtyBonusAllowed: () => true }, coordinator?: GemSourceOrchestrator) {
  const requestId=checkKey(key); const clean=input.comment?.trim()||null; const fp=repository.fingerprint({operation:'create-xp',pathId:studentId,category:input.category,baseXp:input.baseXp,comment:clean});
  const work=(database:Database.Database,tx?:GemSourceTx)=>{ const existing=repository.findEventByRequest(database,teacherId,requestId); if(existing){if((database.prepare('SELECT request_fingerprint AS value FROM xp_evidence_events WHERE id=?').get(existing.id) as any).value!==fp)throw new ApiError('CONFLICT',409,'Idempotency-Key was already used for a different request.'); if(tx)coordinator!.applyXp(tx,transitionIds(database,'source_event_id',existing.id)); return {event:existing,summary:repository.summary(database,existing.studentId,existing.academicYearId),replay:true};} const context=writable(roster.getOwnedStudentAcademicYearContext(database,teacherId,studentId)); const allowed=Boolean(eligibility.specialtyBonusAllowed()); const specialty=context.student.specialty; const categoryAtAward=categoryForSpecialty(specialty); const bonus=Boolean(allowed&&categoryAtAward===input.category); roster.lockStudentGroupCorrection(database,teacherId,studentId); const created=repository.createEvent(database,{id:randomUUID(),teacherId,studentId,academicYearId:context.year.id,category:input.category,baseXp:input.baseXp,specialtyAtAward:specialty,specialtyCategoryAtAward:categoryAtAward,bonusEligibleAtAward:bonus,specialtyBonusXp:bonus?1:0,effectiveXp:input.baseXp+(bonus?1:0),comment:clean,createdAt:now(),requestId,fingerprint:fp}); if(tx)coordinator!.applyXp(tx,created.transitionIds); return {event:created.event,summary:repository.summary(database,studentId,context.year.id),replay:false}; };
  return coordinator?runImmediateTransaction(db,fp,tx=>work(tx.db,tx)):repository.withTransaction(db,()=>work(db));
}
export function reverse(db: Database.Database, teacherId: string, eventId: string, input: { reason?: string }, key: string, coordinator?: GemSourceOrchestrator) { const requestId=checkKey(key); const clean=input.reason?.trim()||null; const fp=repository.fingerprint({operation:'reverse-xp',pathId:eventId,reason:clean}); const work=(database:Database.Database,tx?:GemSourceTx)=>{const existing=repository.findReversalByRequest(database,teacherId,requestId);if(existing){if(existing.requestFingerprint!==fp)throw new ApiError('CONFLICT',409,'Idempotency-Key was already used for a different request.');if(tx)coordinator!.applyXp(tx,transitionIds(database,'source_reversal_id',existing.id));return {reversal:existing,summary:repository.summary(database,existing.studentId,existing.academicYearId),replay:true};}const event=repository.findEvent(database,teacherId,eventId);if(!event)throw new ApiError('NOT_FOUND',404,'XP evidence not found.');writable(roster.getOwnedStudentAcademicYearContextForYear(database,teacherId,event.studentId,event.academicYearId));const result=repository.reverseEvent(database,{id:randomUUID(),teacherId,eventId,reason:clean,createdAt:now(),requestId,fingerprint:fp});if(tx)coordinator!.applyXp(tx,result.transitionIds);return {reversal:result.reversal,summary:repository.summary(database,event.studentId,event.academicYearId),replay:false};};return coordinator?runImmediateTransaction(db,fp,tx=>work(tx.db,tx)):repository.withTransaction(db,()=>work(db)); }
export function getSummary(db: Database.Database, teacherId: string, studentId: string, yearId: string) { roster.getOwnedStudentAcademicYearContextForYear(db,teacherId,studentId,yearId); return repository.summary(db,studentId,yearId); }
export function listEvidence(db: Database.Database, teacherId: string, studentId: string, yearId: string, cursor: {createdAt:string;id:string}|null, limit:number) { getSummary(db,teacherId,studentId,yearId); const rows=repository.listEvents(db,teacherId,studentId,yearId,cursor,limit); const hasMore=rows.length>limit; return {items:hasMore?rows.slice(0,limit):rows,nextCursor:hasMore?{createdAt:rows[limit-1].createdAt,id:rows[limit-1].id}:null}; }
export function groupSummaries(db: Database.Database, teacherId: string, groupId: string, yearId: string) { const group=db.prepare('SELECT id,academic_year_id AS academicYearId FROM groups WHERE id=? AND owner_teacher_id=?').get(groupId,teacherId) as any;if(!group||group.academicYearId!==yearId)throw new ApiError('NOT_FOUND',404,'Group not found.');const rows=repository.groupSummaryRows(db,groupId,yearId);return {groupId,academicYearId:yearId,summaries:rows.map(row=>({studentId:row.studentId,summary:{studentId:row.studentId,academicYearId:yearId,annualEffectiveXp:Number(row.annualEffectiveXp),level:levelForTotal(Number(row.annualEffectiveXp)),progress:progressForTotal(Number(row.annualEffectiveXp)),badges:row.badges?row.badges.split(';;').map(value=>{const [category,label,unlockedAt]=value.split('|');return {category,label,unlockedAt};}):[]}}))}; }
function levelForTotal(total:number): 1|2|3|4|5|6|7|8 { let level=1;for(const threshold of [10,25,45,70,100,135,175])if(total>=threshold)level+=1;return level as 1|2|3|4|5|6|7|8; }
function progressForTotal(total:number) { const level=levelForTotal(total);const thresholds=[0,10,25,45,70,100,135,175];return level===8?{current:0,required:0,nextLevel:null,isMaxLevel:true}:{current:total-thresholds[level-1],required:thresholds[level]-thresholds[level-1],nextLevel:level+1,isMaxLevel:false}; }
