import { useEffect, useState } from 'react';
import { workspaceApi, type AcademicYear, type Group, type ApiFailure, type Calendar, type Session } from './workspace-api';

type TermDraft = { code:'T1'|'T2'|'T3'; startsOn:string; endsOn:string };
type SlotDraft = { groupId:string; weekday:number; startsAt:string; endsAt:string };
type Status = { configured:boolean; canReplace:boolean; eligible:boolean; reason:'ACTIVE_SESSION'|'UNCONFIGURED'|'OUTSIDE_TERM'|'HOLIDAY'|'OUTSIDE_TIMETABLE'|'USED_SLOT_DATE'|'ELIGIBLE'; active:Session|null };
export const weekdays = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
export const eligibilityMessages:Record<Status['reason'],string> = { ACTIVE_SESSION:'A class session is already active.', UNCONFIGURED:'Configure the calendar before starting class.', OUTSIDE_TERM:'Today is outside the configured terms.', HOLIDAY:'No class today: this date is a configured holiday.', OUTSIDE_TIMETABLE:"The current time is outside this group's timetable.", USED_SLOT_DATE:'This period has already been used today.', ELIGIBLE:'Class can start now.' };
function defaultTerms(year: AcademicYear): TermDraft[] { const start=new Date(`${year.startsOn}T00:00:00Z`), end=new Date(`${year.endsOn}T00:00:00Z`), span=Math.floor((end.getTime()-start.getTime())/86400000)+1; const date=(offset:number)=>new Date(start.getTime()+offset*86400000).toISOString().slice(0,10); const first=Math.floor(span/3), second=Math.floor(2*span/3); return [{code:'T1',startsOn:date(0),endsOn:date(first-1)},{code:'T2',startsOn:date(first),endsOn:date(second-1)},{code:'T3',startsOn:date(second),endsOn:year.endsOn}]; }

export function CalendarControls({ year, group, onSessionChange }: { year: AcademicYear; group: Group; onSessionChange?: (session: Session | null) => void }) {
  const [calendar, setCalendar] = useState<Calendar | null>(null); const [status, setStatus] = useState<Status|null>(null); const [timezone,setTimezone]=useState('Europe/Paris'); const [terms,setTerms]=useState<TermDraft[]>(()=>defaultTerms(year)); const [slots,setSlots]=useState<SlotDraft[]>([]); const [editing,setEditing]=useState(false); const [pending,setPending]=useState(false); const [message,setMessage]=useState(''); const [startKey,setStartKey]=useState<string|null>(null); const [endKey,setEndKey]=useState<string|null>(null); const [endedSession,setEndedSession]=useState<Session|null>(null);
  function loadDraft(value:Calendar) { if(!value.configured){setTimezone('Europe/Paris');setTerms(defaultTerms(year));setSlots([{groupId:group.id,weekday:1,startsAt:'08:00',endsAt:'09:00'}]);return;} setTimezone(value.timezone);setTerms(value.terms.map(({code,startsOn,endsOn})=>({code,startsOn,endsOn})));setSlots(value.slots.map(({groupId,weekday,startsAt,endsAt})=>({groupId,weekday,startsAt,endsAt}))); }
  async function refresh(notify=true) { const [loaded,current]=await Promise.all([workspaceApi.calendar(year.id),workspaceApi.sessionStatus(group.id,year.id)]);setCalendar(loaded);setStatus(current);if(notify)onSessionChange?.(current.active);if(loaded.configured&&!editing)loadDraft(loaded); }
  useEffect(()=>{let cancelled=false;setEndedSession(null);Promise.all([workspaceApi.calendar(year.id),workspaceApi.sessionStatus(group.id,year.id)]).then(([loaded,current])=>{if(cancelled)return;setCalendar(loaded);setStatus(current);onSessionChange?.(current.active);loadDraft(loaded);}).catch(()=>{if(!cancelled)setMessage('Calendar status is unavailable. Retry.');});return()=>{cancelled=true;};},[year.id,group.id]);
  async function save(event:React.FormEvent){event.preventDefault();if(pending)return;setPending(true);setMessage('');try{const other=calendar?.configured?calendar.slots.filter(slot=>slot.groupId!==group.id).map(({groupId,weekday,startsAt,endsAt})=>({groupId,weekday,startsAt,endsAt})):[];await workspaceApi.replaceCalendar(year.id,{timezone,terms,holidays:calendar?.configured?calendar.holidays.map(({startsOn,endsOn})=>({startsOn,endsOn})):[],slots:[...other,...slots]});setEditing(false);await refresh();setMessage('Calendar saved.');}catch(error){const failure=error as ApiFailure;setMessage(failure.status===409?'Calendar changed or is already in use.':failure.message);}finally{setPending(false);}}
  function cancel(){if(calendar)loadDraft(calendar);setEditing(false);setMessage('');}
  async function action(kind:'start'|'end'){if(pending||!status)return;setPending(true);setMessage('');try{if(kind==='start'){const key=startKey??crypto.randomUUID();setStartKey(key);await workspaceApi.startSession(group.id,year.id,key);setStartKey(null);await refresh();}else if(status.active){const key=endKey??crypto.randomUUID();setEndKey(key);const result=await workspaceApi.endSession(status.active.id,key);setEndKey(null);setEndedSession(result.value);onSessionChange?.(result.value);await refresh(false);}}catch(error){setMessage((error as Error).message);}finally{setPending(false);}}
  function addSlot(){setSlots(value=>[...value,{groupId:group.id,weekday:1,startsAt:'08:00',endsAt:'09:00'}]);}
  if(!status||!calendar)return <section className="panel" aria-label="Class session controls"><p className="muted">Loading class session…</p></section>;
  const selectedSlots=slots.filter(slot=>slot.groupId===group.id);
  return <section className="panel" aria-label="Class session controls"><p className="eyebrow">REAL CLASS SESSION</p><h2>Class calendar</h2>{(!calendar.configured||editing)&&<form onSubmit={save}><label>Timezone<input required value={timezone} onChange={event=>setTimezone(event.target.value)} /></label>{terms.map((term,index)=><div className="setup-dates" key={term.code}><label>{term.code} starts<input type="date" required value={term.startsOn} onChange={event=>setTerms(values=>values.map((value,current)=>current===index?{...value,startsOn:event.target.value}:value))} /></label><label>{term.code} ends<input type="date" required value={term.endsOn} onChange={event=>setTerms(values=>values.map((value,current)=>current===index?{...value,endsOn:event.target.value}:value))} /></label></div>)}<fieldset><legend>Selected timetable periods</legend>{selectedSlots.map((slot,index)=><div className="setup-dates" key={`${index}-${slot.weekday}-${slot.startsAt}`}><label>Weekday<select aria-label={`Weekday for period ${index+1}`} value={slot.weekday} onChange={event=>setSlots(values=>values.map((value,current)=>current===values.findIndex(item=>item===slot)?{...value,weekday:Number(event.target.value)}:value))}>{weekdays.map((label,day)=><option key={label} value={day+1}>{label} ({day+1})</option>)}</select></label><label>Starts<input type="time" required value={slot.startsAt} onChange={event=>setSlots(values=>values.map((value,current)=>current===values.findIndex(item=>item===slot)?{...value,startsAt:event.target.value}:value))}/></label><label>Ends<input type="time" required value={slot.endsAt} onChange={event=>setSlots(values=>values.map((value,current)=>current===values.findIndex(item=>item===slot)?{...value,endsAt:event.target.value}:value))}/></label><button type="button" className="quiet-button" onClick={()=>setSlots(values=>values.filter(item=>item!==slot))}>Remove</button></div>)}<button type="button" className="quiet-button" onClick={addSlot}>Add period</button></fieldset><div className="form-actions"><button type="submit" disabled={pending}>Save calendar</button>{calendar.configured&&<button type="button" className="quiet-button" disabled={pending} onClick={cancel}>Cancel</button>}</div></form>}{calendar.configured&&!editing&&<><p className="muted">{status.active?`Started ${status.active.localDate} (${status.active.timezone})`:eligibilityMessages[status.reason]}</p>{status.canReplace&&<button type="button" className="setup-toggle" onClick={()=>setEditing(true)}>Edit calendar</button>}{status.active?<button type="button" disabled={pending} onClick={()=>action('end')}>Finalizar clase</button>:<button type="button" disabled={pending||!status.eligible} onClick={()=>action('start')}>Comenzar clase</button>}</>}{message&&<p className="status" role="status">{message}</p>}{endedSession&&<span className="sr-only">Ended session {endedSession.id}</span>}</section>;
}
