import { useEffect, useState } from 'react';
import { workspaceApi, type AcademicYear, type ApiFailure, type Calendar, type Group, type SessionStatus, type Session } from './workspace-api';

type TermDraft = { code:'T1'|'T2'|'T3'; startsOn:string; endsOn:string };
type SlotDraft = { groupId:string; weekday:number; startsAt:string; endsAt:string };
export const weekdays = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
export const eligibilityMessages:Record<SessionStatus['reason'],string> = { ACTIVE_SESSION:'Hay una clase activa. Finalízala antes de comenzar otra.', ARCHIVED_YEAR:'Este curso académico está archivado. No se pueden comenzar clases.', UNCONFIGURED:'Configura el calendario para preparar esta clase.', OUTSIDE_TERM:'Hoy está fuera de los trimestres configurados.', HOLIDAY:'Hoy no hay clase: es un día festivo configurado.', NO_CLASS_DAY:'Hoy no hay clase programada para este grupo.', OUTSIDE_TIMETABLE:'No hay una clase programada en este momento.', USED_SLOT_DATE:'Este periodo ya se utilizó. Consulta la próxima clase.', ELIGIBLE:'Puedes comenzarla ahora.' };
function defaultTerms(year:AcademicYear):TermDraft[]{const start=new Date(`${year.startsOn}T00:00:00Z`),end=new Date(`${year.endsOn}T00:00:00Z`),span=Math.floor((end.getTime()-start.getTime())/86400000)+1,date=(offset:number)=>new Date(start.getTime()+offset*86400000).toISOString().slice(0,10),first=Math.floor(span/3),second=Math.floor(2*span/3);return[{code:'T1',startsOn:date(0),endsOn:date(first-1)},{code:'T2',startsOn:date(first),endsOn:date(second-1)},{code:'T3',startsOn:date(second),endsOn:year.endsOn}];}
function occurrenceText(value:SessionStatus['nextClass']){return value?`${value.weekdayLabel}, ${value.localDate}, ${value.startsAt}–${value.endsAt}`:'';}

export function CalendarControls({year,group,onSessionChange}:{year:AcademicYear;group:Group;onSessionChange?:(session:Session|null)=>void}){
 const [calendar,setCalendar]=useState<Calendar|null>(null),[status,setStatus]=useState<SessionStatus|null>(null),[timezone,setTimezone]=useState('Europe/Paris'),[terms,setTerms]=useState<TermDraft[]>(()=>defaultTerms(year)),[slots,setSlots]=useState<SlotDraft[]>([]),[editing,setEditing]=useState(false),[pending,setPending]=useState(false),[message,setMessage]=useState(''),[loadError,setLoadError]=useState(''),[startKey,setStartKey]=useState<string|null>(null),[endKey,setEndKey]=useState<string|null>(null),[endedSession,setEndedSession]=useState<Session|null>(null);
 function loadDraft(value:Calendar){if(!value.configured){setTimezone('Europe/Paris');setTerms(defaultTerms(year));setSlots([{groupId:group.id,weekday:1,startsAt:'08:00',endsAt:'09:00'}]);return;}setTimezone(value.timezone);setTerms(value.terms.map(({code,startsOn,endsOn})=>({code,startsOn,endsOn})));setSlots(value.slots.map(({groupId,weekday,startsAt,endsAt})=>({groupId,weekday,startsAt,endsAt})));}
 async function refresh(){try{setLoadError('');const [loaded,current]=await Promise.all([workspaceApi.calendar(year.id),workspaceApi.sessionStatus(group.id,year.id)]);setCalendar(loaded);setStatus(current);onSessionChange?.(current.activeForSelectedGroup?current.active:endedSession);if(loaded.configured&&!editing)loadDraft(loaded);}catch{setLoadError('No se puede cargar el estado de la clase.');onSessionChange?.(endedSession);}}
 useEffect(()=>{let cancelled=false;setCalendar(null);setStatus(null);setEndedSession(null);setMessage('');Promise.all([workspaceApi.calendar(year.id),workspaceApi.sessionStatus(group.id,year.id)]).then(([loaded,current])=>{if(cancelled)return;setCalendar(loaded);setStatus(current);onSessionChange?.(current.activeForSelectedGroup?current.active:null);loadDraft(loaded);}).catch(()=>{if(!cancelled){setLoadError('No se puede cargar el estado de la clase.');onSessionChange?.(null);}});return()=>{cancelled=true;};},[year.id,group.id]);
 async function save(event:React.FormEvent){event.preventDefault();if(pending)return;setPending(true);setMessage('');try{const other=calendar?.configured?calendar.slots.filter(slot=>slot.groupId!==group.id).map(({groupId,weekday,startsAt,endsAt})=>({groupId,weekday,startsAt,endsAt})):[];await workspaceApi.replaceCalendar(year.id,{timezone,terms,holidays:calendar?.configured?calendar.holidays.map(({startsOn,endsOn})=>({startsOn,endsOn})):[],slots:[...other,...slots]});setEditing(false);await refresh();setMessage('Calendario guardado.');}catch(error){const failure=error as ApiFailure;setMessage(failure.status===409?'El calendario ha cambiado o ya está en uso.':failure.message);}finally{setPending(false);}}
 async function action(kind:'start'|'end'){if(pending||!status)return;setPending(true);setMessage('');try{if(kind==='start'){const key=startKey??crypto.randomUUID();setStartKey(key);await workspaceApi.startSession(group.id,year.id,key);setStartKey(null);await refresh();}else if(status.activeForSelectedGroup&&status.active){const key=endKey??crypto.randomUUID();setEndKey(key);const result=await workspaceApi.endSession(status.active.id,key);setEndedSession(result.value);setEndKey(null);await refresh();onSessionChange?.(result.value);}}catch(error){setMessage((error as Error).message);}finally{setPending(false);}}
 function cancel(){if(calendar)loadDraft(calendar);setEditing(false);setMessage('');}
 function addSlot(){setSlots(value=>[...value,{groupId:group.id,weekday:1,startsAt:'08:00',endsAt:'09:00'}]);}
 if(loadError)return <section className="panel" aria-label="Class session controls"><p className="error" role="alert">{loadError}</p><button type="button" onClick={()=>void refresh()}>Reintentar</button></section>;
 if(!status||!calendar)return <section className="panel" aria-label="Class session controls"><p className="muted">Cargando la preparación de la clase…</p></section>;
 const selectedSlots=slots.filter(slot=>slot.groupId===group.id), foreignActive=Boolean(status.active&&!status.activeForSelectedGroup);
 return <section className="panel" aria-label="Class session controls"><p className="eyebrow">PREPARACIÓN DE CLASE</p><h2>Clase real</h2>
   <div aria-label="Class preparation status"><p className={status.eligible?'status':'read-only-note'} role="status">{status.message}</p>{status.nextClass&&<p className="muted">Próxima clase: {occurrenceText(status.nextClass)}</p>}{foreignActive&&<p className="error" role="alert">Hay una clase activa en otro grupo. Ve a ese grupo y finalízala antes de comenzar otra.</p>}</div>
   {status.activeForSelectedGroup&&status.active&&<div className="setup-actions"><button type="button" onClick={()=>void action('end')} disabled={pending}>{pending?'Guardando…':'Finalizar clase'}</button></div>}
   {!foreignActive&&<button type="button" onClick={()=>void action('start')} disabled={!status.eligible||pending} title={!status.eligible?status.message:undefined}>{pending?'Guardando…':'Comenzar clase'}</button>}
   <div className="calendar-editor"><h3>Calendario</h3>{!editing&&calendar.configured&&<button type="button" className="quiet-button" onClick={()=>setEditing(true)} disabled={!calendar.canReplace}>Editar calendario</button>}{calendar.configured&&status.reason!=='UNCONFIGURED'&&!editing&&<p className="muted">El calendario está configurado. La preparación y la edición son independientes.</p>}{(!calendar.configured||editing)&&<form onSubmit={save}><label>Zona horaria<input required value={timezone} onChange={event=>setTimezone(event.target.value)} /></label>{terms.map((term,index)=><div className="setup-dates" key={term.code}><label>{term.code} empieza<input type="date" required value={term.startsOn} onChange={event=>setTerms(values=>values.map((value,current)=>current===index?{...value,startsOn:event.target.value}:value))}/></label><label>{term.code} termina<input type="date" required value={term.endsOn} onChange={event=>setTerms(values=>values.map((value,current)=>current===index?{...value,endsOn:event.target.value}:value))}/></label></div>)}<fieldset><legend>Periodos del grupo seleccionado</legend>{selectedSlots.map((slot,index)=><div className="setup-dates" key={`${index}-${slot.weekday}-${slot.startsAt}`}><label>Día<select aria-label={`Weekday for period ${index+1}`} value={slot.weekday} onChange={event=>setSlots(values=>values.map((value,current)=>current===values.findIndex(item=>item===slot)?{...value,weekday:Number(event.target.value)}:value))}>{weekdays.map((label,day)=><option key={label} value={day+1}>{label}</option>)}</select></label><label>Empieza<input type="time" required value={slot.startsAt} onChange={event=>setSlots(values=>values.map((value,current)=>current===values.findIndex(item=>item===slot)?{...value,startsAt:event.target.value}:value))}/></label><label>Termina<input type="time" required value={slot.endsAt} onChange={event=>setSlots(values=>values.map((value,current)=>current===values.findIndex(item=>item===slot)?{...value,endsAt:event.target.value}:value))}/></label><button type="button" className="quiet-button" onClick={()=>setSlots(values=>values.filter(item=>item!==slot))}>Quitar</button></div>)}<button type="button" className="quiet-button" onClick={addSlot}>Añadir periodo</button></fieldset><div className="setup-actions"><button type="submit" disabled={pending}>{pending?'Guardando…':'Guardar calendario'}</button>{editing&&<button type="button" className="quiet-button" onClick={cancel} disabled={pending}>Cancelar</button>}</div></form>}{message&&<p className="status" role="status">{message}</p>}</div>
 </section>;
}
