import { useEffect, useState } from 'react';
import { workspaceApi, type AcademicYear, type Group, type ApiFailure, type Calendar, type Session } from './workspace-api';

type TermDraft = { code:'T1'|'T2'|'T3'; startsOn:string; endsOn:string };
function defaultTerms(year: AcademicYear): TermDraft[] { const start=new Date(`${year.startsOn}T00:00:00Z`), end=new Date(`${year.endsOn}T00:00:00Z`), span=Math.floor((end.getTime()-start.getTime())/86400000)+1; const date=(offset:number)=>new Date(start.getTime()+offset*86400000).toISOString().slice(0,10); const first=Math.floor(span/3), second=Math.floor(2*span/3); return [{code:'T1',startsOn:date(0),endsOn:date(first-1)},{code:'T2',startsOn:date(first),endsOn:date(second-1)},{code:'T3',startsOn:date(second),endsOn:year.endsOn}]; }

export function CalendarControls({ year, group, onSessionChange }: { year: AcademicYear; group: Group; onSessionChange?: (session: Session | null) => void }) {
  const [calendar, setCalendar] = useState<Calendar | null>(null);
  const [status, setStatus] = useState<{ configured:boolean; eligible:boolean; active:Session|null } | null>(null);
  const [timezone, setTimezone] = useState('Europe/Paris');
  const [terms, setTerms] = useState<TermDraft[]>(() => defaultTerms(year));
  const [startsAt, setStartsAt] = useState('08:00');
  const [endsAt, setEndsAt] = useState('09:00');
  const [pending, setPending] = useState(false); const [message, setMessage] = useState('');
  const [startKey, setStartKey] = useState<string|null>(null); const [endKey, setEndKey] = useState<string|null>(null);
  async function refresh() { const [loaded, current] = await Promise.all([workspaceApi.calendar(year.id), workspaceApi.sessionStatus(group.id, year.id)]); setCalendar(loaded); setStatus(current); onSessionChange?.(current.active); if (loaded.configured) { setTimezone(loaded.timezone); setTerms(loaded.terms.map(({code,startsOn,endsOn})=>({code,startsOn,endsOn}))); const slot=loaded.slots.find(value=>value.groupId===group.id); if(slot){setStartsAt(slot.startsAt);setEndsAt(slot.endsAt);} } }
  useEffect(() => { let cancelled=false; Promise.all([workspaceApi.calendar(year.id),workspaceApi.sessionStatus(group.id,year.id)]).then(([loaded,current])=>{if(!cancelled){setCalendar(loaded);setStatus(current);onSessionChange?.(current.active);}}).catch(()=>{if(!cancelled)setMessage('Calendar status is unavailable.');}); return ()=>{cancelled=true;}; }, [year.id,group.id]);
  async function save(event: React.FormEvent) { event.preventDefault(); if(pending)return; setPending(true);setMessage(''); try { await workspaceApi.replaceCalendar(year.id,{timezone,terms,holidays:[],slots:[{groupId:group.id,weekday:1,startsAt,endsAt}]}); await refresh();setMessage('Calendar saved.'); } catch(error){const failure=error as ApiFailure;setMessage(failure.status===409?'Calendar changed or is already in use.':failure.message); } finally{setPending(false);} }
  async function action(kind:'start'|'end') { if(pending||!status)return; setPending(true);setMessage('');try { if(kind==='start') { const key=startKey??crypto.randomUUID(); setStartKey(key); await workspaceApi.startSession(group.id,year.id,key); setStartKey(null); } else if(status.active) { const key=endKey??crypto.randomUUID(); setEndKey(key); await workspaceApi.endSession(status.active.id,key); setEndKey(null); } await refresh(); } catch(error){setMessage((error as Error).message);}finally{setPending(false);} }
  if(!status||!calendar) return <section className="panel" aria-label="Class session controls"><p className="muted">Loading class session…</p></section>;
  return <section className="panel" aria-label="Class session controls"><p className="eyebrow">REAL CLASS SESSION</p><h2>Class calendar</h2>{!calendar.configured ? <form onSubmit={save}><label>Timezone<input required value={timezone} onChange={event=>setTimezone(event.target.value)} /></label>{terms.map((term,index)=><div className="setup-dates" key={term.code}><label>{term.code} starts<input type="date" required value={term.startsOn} onChange={event=>setTerms(values=>values.map((value,current)=>current===index?{...value,startsOn:event.target.value}:value))} /></label><label>{term.code} ends<input type="date" required value={term.endsOn} onChange={event=>setTerms(values=>values.map((value,current)=>current===index?{...value,endsOn:event.target.value}:value))} /></label></div>)}<div className="setup-dates"><label>Starts<input type="time" required value={startsAt} onChange={event=>setStartsAt(event.target.value)} /></label><label>Ends<input type="time" required value={endsAt} onChange={event=>setEndsAt(event.target.value)} /></label></div><button disabled={pending}>Save calendar</button></form> : <><p className="muted">{status.active ? `Started ${status.active.localDate} (${status.active.timezone})` : status.eligible ? 'Class can start now.' : 'No class is eligible at this time.'}</p>{status.active ? <button type="button" disabled={pending} onClick={()=>action('end')}>Finalizar clase</button> : <button type="button" disabled={pending||!status.eligible} onClick={()=>action('start')}>Comenzar clase</button>}</>}{message&&<p className="status" role="status">{message}</p>}</section>;
}
