import { useEffect, useRef, useState } from 'react';
import { workspaceApi, type ApiFailure, type TeacherStudent, type XpCategory, type XpSummary } from './workspace-api';
import type { WorkspaceStudentContext } from './workspace-state';
import { FastActionShell } from './FastActionShell';
import { UndoBanner } from './UndoBanner';

const categories:XpCategory[]=['COMMUNICATION','PRECISION','CONSISTENCY','COLLABORATION'];
function RegisterXp({studentId,summary,onSummary,onFeedback,onUndo,contextKey}:{studentId:string;summary:XpSummary|null;onSummary:(summary:XpSummary)=>void;onFeedback:(message:string)=>void;onUndo:(eventId:string)=>void;contextKey:string}) { const [category,setCategory]=useState<XpCategory|null>(null); const [pending,setPending]=useState(false); const [noteOpen,setNoteOpen]=useState(false); const [comment,setComment]=useState(''); const [operationKey,setOperationKey]=useState<string|null>(null); const previousContext=useRef(contextKey); useEffect(()=>{if(previousContext.current!==contextKey){previousContext.current=contextKey;setOperationKey(null);setCategory(null);setComment('');}},[contextKey]); async function submit(baseXp:1|2|3){if(!category||pending)return;const key=operationKey??crypto.randomUUID();setOperationKey(key);setPending(true);try{const result=await workspaceApi.registerXp(studentId,{category,baseXp,...(comment.trim()?{comment:comment.trim()}: {})},undefined,key);onSummary(result.value.summary);onFeedback(`Base XP +${baseXp} · ${result.value.event.specialtyBonusXp ? 'Specialty bonus +1' : 'No specialty bonus'} · Effective XP +${result.value.event.effectiveXp}`);onUndo(result.value.event.id);setOperationKey(null);setCategory(null);setComment('');}catch(caught){const failure=caught as ApiFailure;if(typeof failure.status==='number'&&failure.status>=400&&failure.status<500)setOperationKey(null);onFeedback('Could not register XP. Try again.');}finally{setPending(false);}} return <section className="xp-action" aria-label="Register XP"><h3>Register XP</h3>{!category?<div className="xp-categories">{categories.map(value=><button type="button" key={value} disabled={pending} onClick={()=>{setOperationKey(null);setCategory(value);}}>{value}</button>)}</div>:<><p>{category}</p><div className="xp-values">{([1,2,3] as const).map(value=><button type="button" key={value} disabled={pending} onClick={()=>submit(value)}>+{value}</button>)}</div><button type="button" className="text-button" onClick={()=>setNoteOpen(!noteOpen)}>{noteOpen?'Hide note':'Add note'}</button>{noteOpen&&<textarea maxLength={500} value={comment} onChange={event=>setComment(event.target.value)} aria-label="Optional XP note" />}</>}</section>; }
export function StudentPanel({ student, context, historical, feedback, undo, onClose, originRef, onUndoResult, summary, onSummary, onFeedback, onUndo }: { student: TeacherStudent | null; context: WorkspaceStudentContext | null; historical: boolean; feedback: string; undo: any; onClose: () => void; originRef?: { current: HTMLElement | null }; onUndoResult: (message: string) => void; summary:XpSummary|null; onSummary:(summary:XpSummary)=>void; onFeedback:(message:string)=>void; onUndo:(event:any)=>void }) {
  const headingRef = useRef<HTMLHeadingElement>(null);
  const closeRef = useRef<HTMLButtonElement>(null);
  const previousStudent = useRef<string | null>(null);
  const dialog = typeof window !== 'undefined' && window.innerWidth < 900;
  useEffect(() => { if (student && dialog && student.id !== previousStudent.current) (closeRef.current ?? headingRef.current)?.focus(); previousStudent.current = student?.id ?? null; }, [student, dialog]);
  if (!student || !context) return <aside className="student-panel panel-empty"><p className="muted">Select a student to inspect their classroom context.</p>{feedback && <p role="status" aria-live="polite">{feedback}</p>}</aside>;
  function close() { onClose(); window.requestAnimationFrame(() => originRef?.current?.focus()); }
   return <aside className="student-panel" role={dialog ? 'dialog' : undefined} aria-modal={dialog ? true : undefined} aria-labelledby="student-panel-title"><button ref={closeRef} className="panel-close" type="button" onClick={close} aria-label="Close student panel">×</button><div className="panel-identity"><span className="avatar" aria-hidden="true">{student.avatar === 'default' ? '◌' : '•'}</span><div><h2 ref={headingRef} id="student-panel-title" tabIndex={-1}>{student.realName}</h2><p className="muted">{student.alias}{student.specialty ? ` · ${student.specialty}` : ''}</p></div></div>{summary&&<p className="xp-summary" role="status">Annual XP: {summary.annualEffectiveXp} · Level {summary.level}{summary.badges.length?` · ${summary.badges.map(b=>b.label).join(', ')}`:''}</p>}{historical || student.archivedAt ? <p className="read-only-note" role="status">Historical record · read-only</p> : <RegisterXp studentId={student.id} summary={summary} contextKey={`${context.academicYearId}:${context.groupId}:${context.studentId}`} onSummary={onSummary} onFeedback={onFeedback} onUndo={onUndo} />}{feedback && <p role="status" aria-live="polite">{feedback}</p>}<UndoBanner opportunity={undo} onResult={onUndoResult} /></aside>;
}
