import { useEffect, useRef, useState } from 'react';
import { activeAssessmentContexts, workspaceApi, type AdvantageRedemption, type ApiFailure, type AssessmentContext, type CoinReward, type CoinSummary, type TeacherStudent, type XpCategory, type XpSummary } from './workspace-api';
import type { WorkspaceStudentContext } from './workspace-state';
import { UndoBanner } from './UndoBanner';

const categories: XpCategory[] = ['COMMUNICATION', 'PRECISION', 'CONSISTENCY', 'COLLABORATION'];

function RegisterXp({ studentId, onSummary, onFeedback, onUndo, contextKey }: { studentId: string; onSummary: (summary: XpSummary) => void; onFeedback: (message: string) => void; onUndo: (event: { id: string }) => void; contextKey: string }) {
  const [category, setCategory] = useState<XpCategory | null>(null); const [pending, setPending] = useState(false); const [comment, setComment] = useState(''); const [operationKey, setOperationKey] = useState<string | null>(null); const previousContext = useRef(contextKey);
  useEffect(() => { if (previousContext.current !== contextKey) { previousContext.current = contextKey; setOperationKey(null); setCategory(null); setComment(''); } }, [contextKey]);
  async function submit(baseXp: 1 | 2 | 3) { if (!category || pending) return; const key = operationKey ?? crypto.randomUUID(); setOperationKey(key); setPending(true); try { const result = await workspaceApi.registerXp(studentId, { category, baseXp, ...(comment.trim() ? { comment: comment.trim() } : {}) }, undefined, key); onSummary(result.value.summary); onFeedback(`Base XP +${baseXp} · ${result.value.event.specialtyBonusXp ? 'Specialty bonus +1' : 'No specialty bonus'} · Effective XP +${result.value.event.effectiveXp}`); onUndo(result.value.event); setOperationKey(null); setCategory(null); setComment(''); } catch (caught) { const failure = caught as ApiFailure; if (typeof failure.status === 'number' && failure.status >= 400 && failure.status < 500) setOperationKey(null); onFeedback(failure.status === 401 ? 'Your session expired. Sign in again.' : 'Could not register XP. Try again.'); } finally { setPending(false); } }
   return <section className="xp-action" aria-label="Register XP"><div className="action-heading"><div><p className="eyebrow">FAST CLASSROOM ACTION</p><h3>Register XP</h3></div><span className="action-hint">No comment needed</span></div>{!category ? <div className="xp-categories">{categories.map(value => <button type="button" key={value} disabled={pending} onClick={() => { setOperationKey(null); setCategory(value); }}>{value}</button>)}</div> : <><p className="selected-category">{category}</p><div className="xp-values" aria-label={`${category} XP value`}>{([1, 2, 3] as const).map(value => <button type="button" key={value} disabled={pending} onClick={() => submit(value)}>+{value}</button>)}</div>{pending && <p className="action-status" role="status" aria-live="polite" aria-label="Action feedback">Saving XP…</p>}<button type="button" className="quiet-button" disabled={pending} onClick={() => { setCategory(null); setOperationKey(null); }}>Choose another category</button><details><summary>Add optional note</summary><label htmlFor="xp-note">Note<span className="sr-only"> (optional)</span></label><textarea id="xp-note" value={comment} onChange={event => setComment(event.target.value)} maxLength={240} /></details></>}</section>;
}

function CoinActions({ context, readOnly, onFeedback }: { context: WorkspaceStudentContext; readOnly: boolean; onFeedback: (message: string) => void }) {
  const [summary, setSummary] = useState<CoinSummary | null>(null); const [rewards, setRewards] = useState<CoinReward[]>([]); const [contexts, setContexts] = useState<AssessmentContext[]>([]); const [assessmentContextId, setAssessmentContextId] = useState(''); const [assessmentName, setAssessmentName] = useState(''); const [activeRedemption, setActiveRedemption] = useState<AdvantageRedemption | null>(null); const [pending, setPending] = useState(false); const [error, setError] = useState('');
   useEffect(() => { if (readOnly) return; const controller = new AbortController(); Promise.all([workspaceApi.coins(context.studentId, controller.signal), workspaceApi.coinRewards(controller.signal), workspaceApi.assessmentContexts(context.groupId, controller.signal)]).then(([coins, fixedRewards, availableContexts]) => { setSummary(coins); setRewards(fixedRewards); const writableContexts = activeAssessmentContexts(availableContexts); setContexts(writableContexts); setAssessmentContextId(writableContexts[0]?.id ?? ''); setActiveRedemption(null); setError(''); }).catch((caught: unknown) => { if (caught instanceof DOMException && caught.name === 'AbortError') return; setError('Could not load coin advantages.'); }); return () => controller.abort(); }, [context.studentId, context.groupId, readOnly]);
  async function createOrSelectAssessment(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const name = assessmentName.trim(); if (!name || pending) return; setPending(true); setError(''); try { const result = await workspaceApi.createAssessmentContext(context.groupId, assessmentName); const canonical = result.value; setContexts(current => current.some(item => item.id === canonical.id) ? current : [...current, canonical]); setAssessmentContextId(canonical.id); setAssessmentName(''); onFeedback(result.replayed ? `${canonical.name} selected.` : `${canonical.name} created and selected.`); } catch (caught) { const failure = caught as ApiFailure; setError(failure.status === 422 ? 'Enter an assessment name.' : failure.message); } finally { setPending(false); } }
  async function redeem(reward: CoinReward) { if (!assessmentContextId || pending || activeRedemption) return; setPending(true); setError(''); try { const result = await workspaceApi.redeemAdvantage(context.studentId, assessmentContextId, reward.id); setSummary(current => current ? { ...current, balance: current.balance - reward.cost } : current); setActiveRedemption(result.value); onFeedback(result.replayed ? 'Advantage request replayed.' : `${reward.name} reserved.`); } catch (caught) { const failure = caught as ApiFailure; setError(failure.status === 409 ? 'This assessment already has an advantage.' : failure.message); } finally { setPending(false); } }
  async function reverse() { if (!activeRedemption || pending) return; setPending(true); setError(''); try { await workspaceApi.reverseAdvantage(activeRedemption.id); setSummary(current => current ? { ...current, balance: current.balance + activeRedemption.cost } : current); setActiveRedemption(null); onFeedback('Assessment advantage undone.'); } catch (caught) { const failure = caught as ApiFailure; setError(failure.status === 409 ? 'This assessment advantage is already reversed.' : failure.message); } finally { setPending(false); } }
  if (readOnly) return null;
   return <section className="coin-action panel-section" aria-label="Assessment advantages"><div className="action-heading"><div><p className="eyebrow">ECLIPSE POINTS</p><h3>Assessment advantage</h3></div><strong aria-label="Eclipse Points balance">{summary?.balance ?? '—'} points</strong></div><form className="assessment-context-form" onSubmit={createOrSelectAssessment}><label htmlFor="assessment-name">Create/select Assessment<input id="assessment-name" value={assessmentName} onChange={event => setAssessmentName(event.target.value)} placeholder="e.g. Unit quiz" maxLength={100} /></label><button type="submit" disabled={pending || !assessmentName.trim()}>Create/select Assessment</button></form>{contexts.length ? <label htmlFor="assessment-context">Assessment<select id="assessment-context" value={assessmentContextId} onChange={event => setAssessmentContextId(event.target.value)}>{contexts.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : <p className="muted">Create an assessment to continue.</p>}<div className="coin-rewards">{rewards.map(reward => <button type="button" key={reward.id} disabled={pending || !assessmentContextId || Boolean(activeRedemption) || (summary?.balance ?? 0) < reward.cost} onClick={() => redeem(reward)}>{reward.name} · {reward.cost} points</button>)}</div>{activeRedemption && <button type="button" className="quiet-button" disabled={pending} onClick={reverse}>Undo assessment advantage</button>}{error && <p className="error" role="alert">{error}</p>}</section>;
}

export function StudentPanel({ student, context, historical, feedback, undo, onClose, originRef, onUndoResult, summary, onSummary, onFeedback, onUndo }: { student: TeacherStudent | null; context: WorkspaceStudentContext | null; historical: boolean; feedback: string; undo: any; onClose: () => void; originRef?: { current: HTMLElement | null }; onUndoResult: (message: string) => void; summary: XpSummary | null; onSummary: (summary: XpSummary) => void; onFeedback: (message: string) => void; onUndo: (event: { id: string }) => void }) {
  const headingRef = useRef<HTMLHeadingElement>(null); const closeRef = useRef<HTMLButtonElement>(null); const panelRef = useRef<HTMLElement>(null); const previousStudent = useRef<string | null>(null); const dialog = typeof window !== 'undefined' && window.innerWidth < 900;
  useEffect(() => { if (student && dialog && student.id !== previousStudent.current) (closeRef.current ?? headingRef.current)?.focus(); previousStudent.current = student?.id ?? null; }, [student, dialog]);
  useEffect(() => { if (!dialog || !student) return; const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); onClose(); window.requestAnimationFrame(() => originRef?.current?.focus()); } }; document.addEventListener('keydown', escape); return () => document.removeEventListener('keydown', escape); }, [dialog, student, onClose, originRef]);
  useEffect(() => { if (!dialog || !student) return; const trap = (event: KeyboardEvent) => { if (event.key !== 'Tab') return; const panel = panelRef.current; if (!panel) return; const focusable = [...panel.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), textarea:not([disabled]), select:not([disabled]), summary, a[href], [tabindex]:not([tabindex="-1"])')].filter(element => element.getClientRects().length > 0); if (!focusable.length) return; const first = focusable[0]; const last = focusable[focusable.length - 1]; const active = document.activeElement; if (event.shiftKey && active === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && (active === last || active?.tagName === 'SUMMARY')) { event.preventDefault(); first.focus(); } else if (!panel.contains(active)) { event.preventDefault(); first.focus(); } }; document.addEventListener('keydown', trap); return () => document.removeEventListener('keydown', trap); }, [dialog, student]);
  if (!student || !context) return <aside className="student-panel panel-empty"><p className="muted">Select a student to inspect their classroom context.</p>{feedback && <p role="status" aria-live="polite">{feedback}</p>}</aside>;
  const close = () => { onClose(); window.requestAnimationFrame(() => originRef?.current?.focus()); };
  return <aside ref={panelRef} className="student-panel" role={dialog ? 'dialog' : undefined} aria-modal={dialog ? true : undefined} aria-labelledby="student-panel-title"><button ref={closeRef} className="panel-close" type="button" onClick={close} aria-label="Close student panel">×</button><div className="panel-identity"><span className="avatar" aria-hidden="true">{student.avatar === 'default' ? '◌' : '•'}</span><div><p className="eyebrow">SELECTED STUDENT</p><h2 ref={headingRef} id="student-panel-title" tabIndex={-1}>{student.realName}</h2><p className="muted">{student.alias}</p></div></div><section className="student-facts" aria-label="Student identity and specialty"><span><small>Specialty</small><strong>{student.specialty ?? 'Not assigned'}</strong></span>{summary && <span><small>Annual XP</small><strong>Annual XP: {summary.annualEffectiveXp} · Level {summary.level}</strong></span>}</section>{summary && <div className="xp-progress" aria-label={`${summary.progress.current} of ${summary.progress.required} XP to next level`}><div><span>Progress to Level {summary.progress.nextLevel ?? 'max'}</span><strong>{summary.progress.isMaxLevel ? 'Maximum level' : `${summary.progress.current} / ${summary.progress.required} XP`}</strong></div>{!summary.progress.isMaxLevel && <progress max={summary.progress.required} value={summary.progress.current} />}</div>}{summary?.badges.length ? <p className="badge-callout" role="status">Badge unlocked: {summary.badges.map(badge => badge.label).join(', ')}</p> : null}{historical || student.archivedAt ? <p className="read-only-note" role="status">Historical record · read-only</p> : <><RegisterXp studentId={student.id} contextKey={`${context.academicYearId}:${context.groupId}:${context.studentId}`} onSummary={onSummary} onFeedback={onFeedback} onUndo={onUndo} /><CoinActions context={context} readOnly={historical || Boolean(student.archivedAt)} onFeedback={onFeedback} /></>}{feedback && <p className="feedback" role="status" aria-live="polite">{feedback}</p>}<UndoBanner opportunity={undo} onResult={onUndoResult} /></aside>;
}
