import { useEffect, useRef, useState } from 'react';
import { workspaceApi, type ApiFailure, type TermCloseDto } from './workspace-api';

type Term = { id:string; code:'T1'|'T2'|'T3'; startsOn:string; endsOn:string };
type Props = { context:{ academicYearId:string; groupId:string; readOnly:boolean }; onSelectStudent:(studentId:string) => void; onSessionExpired?:() => void };

export function TermClosePanel({ context, onSelectStudent, onSessionExpired }:Props) {
  const [terms, setTerms] = useState<Term[]>([]); const [termId, setTermId] = useState('');
  const [data, setData] = useState<TermCloseDto|null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [filter, setFilter] = useState<'all'|'pending'>('all'); const [pending, setPending] = useState(false); const [reason, setReason] = useState(''); const [reopen, setReopen] = useState(false); const [retry, setRetry] = useState(0); const keyRef = useRef<string|null>(null);
  const contextKey = `${context.academicYearId}:${context.groupId}`;

  useEffect(() => { keyRef.current = null; setTerms([]); setTermId(''); setData(null); setError(''); setReopen(false); }, [contextKey]);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(''); workspaceApi.calendar(context.academicYearId, controller.signal).then(calendar => { if (controller.signal.aborted) return; const next = calendar.configured ? calendar.terms : []; setTerms(next); setTermId(current => current && next.some(term => term.id === current) ? current : next[0]?.id ?? ''); }).catch((caught:ApiFailure) => { if (caught.name !== 'AbortError') { if (caught.status === 401) onSessionExpired?.(); setError(caught.status === 401 ? 'La sesión ha caducado. Vuelve a iniciar sesión.' : 'No se pudo cargar el calendario. Reintentar.'); } }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [contextKey]);
  useEffect(() => { if (!termId) return; const controller = new AbortController(); setLoading(true); setError(''); setData(null); workspaceApi.termClose(context.groupId, termId, context.academicYearId, controller.signal).then(value => { if (!controller.signal.aborted) setData(value); }).catch((caught:ApiFailure) => { if (caught.name !== 'AbortError') { if (caught.status === 401) onSessionExpired?.(); setError(caught.status === 401 ? 'La sesión ha caducado. Vuelve a iniciar sesión.' : 'No se pudo cargar el cierre trimestral. Reintentar.'); } }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [contextKey, termId, retry]);

  const reload = () => { setData(null); setRetry(value => value + 1); };
  const mutation = async (run:(key:string)=>Promise<unknown>, success:string) => { if (pending) return; setPending(true); setError(''); try { await run(keyRef.current ?? (keyRef.current = crypto.randomUUID())); keyRef.current = null; reload(); } catch (caught) { const failure = caught as ApiFailure; if (failure.status === 401) onSessionExpired?.(); setError(failure.status === 409 ? 'El cierre cambió. Recarga para comparar antes de reintentar.' : failure.status === 401 ? 'La sesión ha caducado. Vuelve a iniciar sesión.' : `${success} No se pudo completar. Reintentar.`); } finally { setPending(false); } };
  async function download() { if (!data?.currentSnapshotVersion || !termId) return; try { const exportFile = await workspaceApi.downloadTermClose(context.groupId, termId, context.academicYearId, data.currentSnapshotVersion); const url = URL.createObjectURL(exportFile.blob); const link = document.createElement('a'); link.href = url; if (exportFile.filename) link.download = exportFile.filename; link.click(); URL.revokeObjectURL(url); } catch (caught) { const failure = caught as ApiFailure; if (failure.status === 401) onSessionExpired?.(); setError(failure.status === 401 ? 'La sesión ha caducado. Vuelve a iniciar sesión.' : 'No se pudo descargar el XLSX. Reintentar.'); } }

  if (loading && !data) return <section className="panel-section term-close-panel" aria-label="Cierre trimestral"><h3>Cierre trimestral</h3><p className="status" role="status">Cargando cierre trimestral…</p></section>;
  return <section className="panel-section term-close-panel" aria-label="Cierre trimestral">
    <div className="action-heading"><div><p className="eyebrow">CIERRE PRIVADO DE GRUPO</p><h3>Cierre trimestral</h3></div>{data?.state === 'CLOSED' && <strong>Versión {data.currentSnapshotVersion}</strong>}</div>
    {error && <p className="error" role="alert">{error} <button type="button" onClick={reload}>Reintentar</button>{error.includes('cambió') && <button type="button" onClick={reload}>Recargar</button>}</p>}
    {!terms.length ? <p className="empty-state">No hay trimestres configurados. Configura el calendario para cerrar el grupo.</p> : <>
      <label htmlFor="term-close-term">Trimestre<select id="term-close-term" aria-label="Trimestre de cierre" value={termId} onChange={event => setTermId(event.target.value)} disabled={pending}><option value="">Selecciona un trimestre</option>{terms.map(term => <option key={term.id} value={term.id}>{term.code}</option>)}</select></label>
      {termId && !data ? <p className="status" role="status">Cargando preparación…</p> : data && <>
         {context.readOnly && <p className="read-only-note" role="status">Curso archivado: solo lectura.</p>}
         {data.b01Warning && <p className="read-only-note" role="status">Aviso B-01: {data.b01Warning} ({data.b01Count} registro{data.b01Count === 1 ? '' : 's'}).</p>}
        {data.state === 'CLOSED' && <div className="term-close-summary"><p>Versión {data.currentSnapshotVersion} · cierre registrado</p>{data.closedAt && <p>{new Date(data.closedAt).toLocaleString('es-ES')}</p>}{data.staleReasons.length > 0 && <p className="read-only-note">El cierre está desactualizado: {data.staleReasons.join(', ')}.</p>}<button type="button" onClick={() => void download()} disabled={pending || context.readOnly}>Exportar XLSX</button>{!context.readOnly && <button type="button" onClick={() => setReopen(true)} disabled={pending}>Reabrir cierre</button>}</div>}
        <p className="term-close-count">{data.readyCount} de {data.activeCount} listos</p>
        <div className="term-close-tools"><label><input type="checkbox" aria-label="Solo pendientes" checked={filter === 'pending'} onChange={event => setFilter(event.target.checked ? 'pending' : 'all')} /> Solo pendientes</label><button type="button" data-action="next-pending" onClick={() => { const next = data.students.find(student => student.rubricState !== 'CLOSED'); if (next) onSelectStudent(next.studentId); }} disabled={!data.students.some(student => student.rubricState !== 'CLOSED') || pending}>Siguiente pendiente</button></div>
        {!data.activeCount ? <p className="empty-state">Este grupo no tiene estudiantes activos.</p> : <div className="term-close-table-wrap"><table className="term-close-table"><caption className="sr-only">Preparación del cierre trimestral</caption><thead><tr><th>Nombre</th><th>Rúbrica</th><th>RT</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{data.students.filter(student => filter === 'all' || student.rubricState !== 'CLOSED').map(student => <tr key={student.studentId}><th scope="row">{student.realName}</th><td>{student.rubricState === 'CLOSED' ? `Cerrada v${student.snapshotVersion}` : 'Pendiente'}</td><td>{student.rtAverage == null ? 'Sin evidencias' : `${student.rtAverage.toFixed(1).replace('.', ',')}/10`}</td><td>{student.rubricState === 'CLOSED' ? 'Listo' : 'Bloquea el cierre'}</td><td><button type="button" onClick={() => onSelectStudent(student.studentId)}>Abrir rúbrica</button>{student.gradeMilli != null && <span className="official-grade">Calificación oficial: {(student.gradeMilli / 1000).toFixed(3).replace('.', ',')}/10</span>}</td></tr>)}</tbody></table></div>}
        {data.state !== 'CLOSED' && <><button type="button" aria-label="Cerrar trimestre" disabled={context.readOnly || pending || !data.ready} onClick={() => void mutation(key => workspaceApi.closeTerm(context.groupId, termId, context.academicYearId, data.revision, key), 'El cierre trimestral')}>Cerrar trimestre</button>{!data.ready && <p className="muted">Falta cerrar la rúbrica de {data.activeCount - data.readyCount} estudiante{data.activeCount - data.readyCount === 1 ? '' : 's'}.</p>}</>}
        {reopen && <div role="dialog" aria-label="Confirmar reapertura"><label>Motivo de reapertura<textarea value={reason} onChange={event => setReason(event.target.value)} /></label><button type="button" disabled={pending || !reason.trim()} onClick={() => void mutation(key => workspaceApi.reopenTerm(context.groupId, termId, context.academicYearId, data.revision, reason.trim(), key), 'La reapertura')}>Confirmar reapertura</button><button type="button" disabled={pending} onClick={() => { setReopen(false); setReason(''); }}>Cancelar</button></div>}
      </>}
    </>}
  </section>;
}
