import { useEffect, useMemo, useReducer, useRef, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { filterStudents } from './search';
import { workspaceApi, type AcademicYear, type Group, type TeacherStudent, type XpSummary } from './workspace-api';
import { initialWorkspaceState, parseContext, reducer, type WorkspaceStudentContext } from './workspace-state';
import { GroupSelector } from './GroupSelector';
import { StudentPanel } from './StudentPanel';
import { StudentRoster } from './StudentRoster';
import { WorkspaceShell } from './WorkspaceShell';
import { YearContextControl } from './YearContextControl';

function SignIn({ onSignedIn }: { onSignedIn: () => void }) {
  const [error, setError] = useState('');
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(''); const data = new FormData(event.currentTarget);
    const response = await fetch('/api/v1/auth/session', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email: data.get('email'), password: data.get('password') }) });
    if (!response.ok) { setError('Sign-in failed. Check your credentials.'); return; }
    onSignedIn();
  }
  return <WorkspaceShell><section className="panel login-panel"><p className="eyebrow">PROTOCOL ECLIPSE · TEACHER ACCESS</p><h1>Open the classroom workspace</h1><p className="muted">Find a student, register the evidence, and keep teaching.</p><form onSubmit={submit}><label htmlFor="workspace-email">Email</label><input id="workspace-email" name="email" type="email" autoComplete="username" required /><label htmlFor="workspace-password">Password</label><input id="workspace-password" name="password" type="password" autoComplete="current-password" required /><button type="submit">Sign in</button>{error && <p className="error" role="alert">{error}</p>}</form></section></WorkspaceShell>;
}

export function WorkspaceApp() {
  useLocation();
  const params = new URLSearchParams(window.location.hash.split('?')[1] ?? window.location.search);
  const [state, dispatch] = useReducer(reducer, { ...initialWorkspaceState, selectedStudentId: parseContext(params.get('student')) });
  const [years, setYears] = useState<AcademicYear[]>([]); const [groups, setGroups] = useState<Group[]>([]); const [students, setStudents] = useState<TeacherStudent[]>([]); const [summaries, setSummaries] = useState<Record<string, XpSummary>>({});
  const [yearId, setYearId] = useState(parseContext(params.get('year'))); const [groupId, setGroupId] = useState(parseContext(params.get('group'))); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [auth, setAuth] = useState(true); const [historical, setHistorical] = useState(false);
  const generation = useRef(0); const originRef = useRef<HTMLElement | null>(null); const searchRef = useRef<HTMLInputElement>(null); const selectedStudentRef = useRef(state.selectedStudentId); selectedStudentRef.current = state.selectedStudentId;
  function clearPrivateState() { setYears([]); setGroups([]); setStudents([]); setSummaries({}); setYearId(null); setGroupId(null); setHistorical(false); dispatch({ type: 'context-changed' }); setError(''); setAuth(false); }
  useEffect(() => { const controller = new AbortController(); workspaceApi.years(false, controller.signal).then(async loaded => { let available = loaded; let historic = false; if (!available.length) { available = await workspaceApi.years(true, controller.signal); historic = true; } setYears(available); setHistorical(historic || Boolean(available.find(year => year.id === yearId)?.archivedAt)); const chosen = available.find(year => year.id === yearId) ?? available[0]; if (chosen) setYearId(chosen.id); else setError('No academic years available'); }).catch((caught: any) => { if (caught.name !== 'AbortError') { if (caught.status === 401) clearPrivateState(); else setError('Could not load academic years. Try again.'); } }).finally(() => setLoading(false)); return () => controller.abort(); }, []);
  useEffect(() => { if (!yearId || !years.some(year => year.id === yearId)) return; const controller = new AbortController(); const current = ++generation.current; dispatch({ type: 'request-started' }); setLoading(true); workspaceApi.groups(yearId, controller.signal).then(loaded => { if (current !== generation.current) return; setGroups(loaded); const chosen = loaded.find(group => group.id === groupId) ?? loaded[0]; setGroupId(chosen?.id ?? null); }).catch((caught: any) => { if (caught.name !== 'AbortError' && current === generation.current) { if (caught.status === 401) clearPrivateState(); else setError(caught.status === 404 ? 'This year is no longer available.' : 'Could not load groups. Try again.'); } }).finally(() => setLoading(false)); return () => controller.abort(); }, [yearId, years]);
  useEffect(() => { if (!groupId || !yearId || !groups.some(group => group.id === groupId)) { setStudents([]); setSummaries({}); return; } const controller = new AbortController(); const current = ++generation.current; setLoading(true); Promise.all([workspaceApi.students(groupId, historical, controller.signal), workspaceApi.xpSummaries(groupId, yearId, controller.signal).catch(() => ({ groupId, academicYearId: yearId, summaries: [] }))]).then(([loaded, summaryResult]) => { if (current !== generation.current) return; setStudents(loaded); setSummaries(Object.fromEntries(summaryResult.summaries.map(item => [item.studentId, item.summary]))); if (selectedStudentRef.current && !loaded.some(student => student.id === selectedStudentRef.current)) dispatch({ type: 'selection-invalidated' }); }).catch((caught: any) => { if (caught.name !== 'AbortError' && current === generation.current) { if (caught.status === 401) clearPrivateState(); else setError(caught.status === 404 ? 'This group is no longer available.' : 'Could not load students. Try again.'); } }).finally(() => setLoading(false)); return () => controller.abort(); }, [groupId, yearId, historical, groups]);
  useEffect(() => { const missing = state.selectedStudentId; if (!loading && missing && !students.some(student => student.id === missing)) dispatch({ type: 'selection-invalidated' }); }, [students, state.selectedStudentId, loading]);
  useEffect(() => { const next = new URLSearchParams(); if (yearId) next.set('year', yearId); if (groupId) next.set('group', groupId); if (state.selectedStudentId) next.set('student', state.selectedStudentId); const target = `#/workspace${next.toString() ? `?${next.toString()}` : ''}`; if (window.location.hash !== `#/${target.slice(2)}`) window.history.replaceState(null, '', `/${target}`); }, [yearId, groupId, state.selectedStudentId]);
  const visibleStudents = useMemo(() => filterStudents(students, state.search), [students, state.search]); const selected = students.find(student => student.id === state.selectedStudentId) ?? null; const context: WorkspaceStudentContext | null = selected && yearId && groupId ? { academicYearId: yearId, groupId, studentId: selected.id, realName: selected.realName, alias: selected.alias, readOnly: historical || Boolean(selected.archivedAt) } : null;
  function setSummary(summary: XpSummary) { setSummaries(current => ({ ...current, [summary.studentId]: summary })); }
  function registerUndo(event: { id: string }) { if (!context) return; dispatch({ type: 'action-result', undo: { actionId: 'xp', studentId: context.studentId, groupId: context.groupId, expiresAt: Date.now() + 10000, label: 'Undo XP registration', undo: async () => { try { const result = await workspaceApi.reverseXp(event.id); setSummary(result.value.summary); return { kind: 'undone' as const, message: 'XP registration undone.' }; } catch { return { kind: 'invalid' as const, message: 'The XP correction could not be applied.' }; } } } }); }
  if (!auth) return <SignIn onSignedIn={() => { setAuth(true); setLoading(true); window.location.reload(); }} />;
  if (loading && !years.length) return <WorkspaceShell><p className="status" role="status">Loading classroom workspace…</p></WorkspaceShell>;
  return <WorkspaceShell><header className="workspace-header"><div><p className="eyebrow">ÉCLIPSE · TEACHER WORKSPACE</p><h1>Classroom workspace</h1><p className="context-line">{years.find(year => year.id === yearId)?.label ?? 'Choose a year'}{groupId ? ` · ${groups.find(group => group.id === groupId)?.name ?? 'Choose a group'}` : ''}</p></div><YearContextControl years={years} value={yearId ?? ''} historical={historical} onChange={id => { setYearId(id); setGroupId(null); setStudents([]); setSummaries({}); dispatch({ type: 'context-changed' }); }} /></header>{error && <p className="error" role="alert">{error} <button type="button" onClick={() => window.location.reload()}>Retry</button></p>}<div className="workspace-toolbar"><GroupSelector groups={groups} value={groupId ?? ''} onChange={id => { setGroupId(id); dispatch({ type: 'context-changed' }); }} /><label className="search-control" htmlFor="student-search">Search students<input ref={searchRef} id="student-search" type="search" value={state.search} placeholder="Name or alias" onChange={event => dispatch({ type: 'search', value: event.target.value })} onKeyDown={event => { if (event.key === 'Escape') { dispatch({ type: 'search', value: '' }); searchRef.current?.focus(); } }} /></label>{state.search && <button type="button" aria-label="Clear student search" onClick={() => { dispatch({ type: 'search', value: '' }); searchRef.current?.focus(); }}>Clear</button>}</div>{historical && <p className="read-only-note" role="status">Historical year — records are read-only.</p>}{!groups.length && !error ? <p className="empty-state">No groups in this year.</p> : <div className="workspace-grid"><section><h2 className="section-title">Roster <span>{visibleStudents.length}</span></h2><StudentRoster students={visibleStudents} summaries={summaries} selectedId={state.selectedStudentId} query={state.search} onSelect={id => { originRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; dispatch({ type: 'select', studentId: id }); }} /></section><StudentPanel student={selected} context={context} historical={historical} feedback={state.feedback} undo={state.undo} summary={selected ? summaries[selected.id] ?? null : null} onSummary={setSummary} onFeedback={message => dispatch({ type: 'action-result', message, undo: null })} onUndo={registerUndo} onClose={() => dispatch({ type: 'select', studentId: '' })} originRef={originRef} onUndoResult={message => dispatch({ type: 'undo-result', message })} /></div>}</WorkspaceShell>;
}
